'use client';
import {useId,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Activity,Layers,Clock,Download,BookOpen} from 'lucide-react';
import {activityData} from '@/core/audit';
import {hasObservation} from '@/core/insights';
import {csv,format,number} from '@/core/metrics';
import type {Snapshot} from '@/core/types';
import {ComparisonBars} from '@/components/insight-charts';
import {Panel,Metric,Proof,Empty,DataTable,download} from '@/components/ui';
import {PageHeading,ObservationBar} from './shared';

export function ActivityLab({s}:{s:Snapshot}){
 const params=useSearchParams(),raw=Number(params.get('records')),count=[15,30,60].includes(raw)?raw:30;
 const [measure,setMeasure]=useState<'cumulativeTransactions'|'transactions'>('cumulativeTransactions');
 const chartId=useId(),available=hasObservation(s,'blocks'),data=activityData(available?s.blocks:[],count);
 const chart=data.rows.map((r,i)=>({x:44+i/Math.max(1,data.rows.length-1)*650,y:number(r[measure])}));
 const max=Math.max(1,...chart.map(p=>p.y??0));
 const line=chart.map(p=>p.y===null?null:`${p.x},${206-p.y/max*160}`);
 const title=measure==='transactions'?'Transactions per returned block':'Cumulative transactions in selected records';
 const exportRows=()=>data.rows.map(r=>({...r,unit:'transactions / gas units',source:s.sources.find(x=>x.id==='blocks')?.url??'',fetchedAt:s.sources.find(x=>x.id==='blocks')?.fetchedAt??'',windowStart:data.first,windowEnd:data.last,coverage:'Selected indexed records only. Missing heights are not zero-transaction blocks.'}));
 return <div className="observatory-v2"><PageHeading eyebrow="OBSERVATORY / ACTIVITY LAB" title="Read the chain, one block at a time" description="Real indexed records, useful comparisons, and the context needed to read them correctly." snapshot={s}/><ObservationBar s={s}/>
 <div className="activity-toolbar"><div className="segmented" aria-label="Activity sample">{[15,30,60].map(n=><button key={n} aria-pressed={count===n} onClick={()=>{const next=new URLSearchParams(params.toString());next.set('records',String(n));window.history.replaceState(null,'','?'+next.toString());}}>Latest {n}</button>)}</div><span className="small muted">{data.rows.length} returned records in view</span><button className="button" disabled={!data.rows.length} onClick={()=>download('gonka-activity.csv',csv(exportRows()),'text/csv')}><Download size={14}/> Export activity</button></div>
 <div className="metric-grid"><Metric label="Transactions in this sample" value={available?data.transactions:null} note="Not network-wide requests or AI tokens" icon={<Activity size={17}/>}/><Metric label="Gas used in this sample" value={available?data.gas:null} note="Execution units, not a GNK fee amount" icon={<Layers size={17}/>}/><Metric label="Observed span" value={data.rows.length>1?data.spanSeconds:null} kind="number" note="Seconds between first and last returned timestamps" icon={<Clock size={17}/>}/><Metric label="Heights absent from sample" value={data.rows.length?data.missingHeights:null} kind="number" note="Does not imply a chain outage or empty blocks" icon={<BookOpen size={17}/>}/></div>
 <div className="reader-note"><BookOpen size={18}/><div><strong>Two token meanings. Two different datasets.</strong> These charts describe blockchain transactions. AI prompt/output tokens require a separate inference dataset.</div><Link href="/learn#glossary">Decode the terms</Link></div>
 <Panel title={title} description="Select a measure. The cumulative series starts at the first selected record—not network genesis." footer={<Proof snapshot={s} ids={['blocks']}/>}>
 <div className="segmented" aria-label="Activity trend measure"><button aria-pressed={measure==='cumulativeTransactions'} onClick={()=>setMeasure('cumulativeTransactions')}>Cumulative sample</button><button aria-pressed={measure==='transactions'} onClick={()=>setMeasure('transactions')}>Per block</button></div>
 {data.rows.length?<figure className="activity-figure" aria-label={title}><svg viewBox="0 0 740 250" role="img" aria-labelledby={chartId}><title id={chartId}>{title}</title>{[0,.25,.5,.75,1].map(part=><g key={part}><line x1="44" x2="694" y1={206-part*160} y2={206-part*160} stroke="var(--border)" strokeDasharray="4 5"/><text x="36" y={210-part*160} textAnchor="end">{format(Math.round(max*part))}</text></g>)}{line.every(Boolean)&&<polyline points={line.join(' ')} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>}{chart.map((p,i)=>p.y===null?null:<circle key={data.rows[i].height} cx={p.x} cy={206-p.y/max*160} r="3" fill="var(--accent)"><title>{`Block ${data.rows[i].height}: ${data.rows[i][measure]} transactions`}</title></circle>)}{[0,Math.floor((data.rows.length-1)/2),data.rows.length-1].filter((v,i,a)=>a.indexOf(v)===i).map(i=><text key={i} x={chart[i].x} y="235" textAnchor={i===0?'start':i===data.rows.length-1?'end':'middle'}>#{data.rows[i].height}</text>)}</svg><figcaption>Record sequence, oldest to newest. Missing heights are not interpolated as empty blocks. Exact values appear in the table below.</figcaption></figure>:<Empty>No indexed records are available. No synthetic chart is substituted.</Empty>}
 <p className="chart-explainer">{data.first&&data.last?`${data.first} → ${data.last} · UTC.`:'Observation window unavailable.'} This is a bounded sample, not a daily total. Refreshing a snapshot does not create new events.</p></Panel>
 <div className="grid-two"><Panel title="How busy are the returned blocks?" description="Count of selected records in each transaction-size band" footer={<Proof snapshot={s} ids={['blocks']}/>}>
 {available?<ComparisonBars label="Block transaction distribution" unit="blocks" rows={data.histogram} source={s.sources.find(x=>x.id==='blocks')} basis="selected indexed records only"/>:<Empty>The block source is unavailable.</Empty>}<p className="chart-explainer">A block with 100 transactions does not necessarily represent 100 AI requests. Some heights may not be returned by this indexer.</p></Panel>
 <Panel title="A quick guide to this chart"><dl className="activity-definitions"><div><dt>Transactions</dt><dd>Operations recorded on chain. They can include transfers or protocol messages.</dd></div><div><dt>Gas used</dt><dd>Reported execution units. Converting these to fees requires the actual transaction’s fee data.</dd></div><div><dt>Cumulative sample</dt><dd>A running total of only the records selected above. Changing the sample changes the starting point.</dd></div><div><dt>Absent heights</dt><dd>Heights between the first and last record that this result does not contain. Their activity is unknown here.</dd></div></dl><Link className="more" href="/developers#reference">Use the same data through the API</Link></Panel></div>
 <Panel title="Inspect every selected record" description="Sortable exact values. No gas amount is converted to an unsafe JavaScript number."><DataTable rows={data.rows} rowKey={r=>String(r.height)} exportName="activity records" source={s.sources.find(x=>x.id==='blocks')} columns={[{key:'height',label:'Block',value:r=>r.height,render:r=><Link className="mono accent" href={'/blocks/'+r.height}>#{r.height}</Link>},{key:'time',label:'Time (UTC)',value:r=>r.time},{key:'transactions',label:'Transactions',value:r=>r.transactions},{key:'cumulative',label:'Cumulative sample',value:r=>r.cumulativeTransactions},{key:'gas',label:'Gas used (units)',value:r=>r.gas}]}/></Panel></div>;
}
