'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Cpu,Layers,ArrowUpRight,BookOpen,ShieldCheck} from 'lucide-react';
import {Panel,Metric,Proof,DataTable,Empty,External,Badge} from '@/components/ui';
import {PageHeading,Watch} from './shared';
import {bech32Address,format,shorten} from '@/core/metrics';
import type {Snapshot} from '@/core/types';

type Section='hardware'|'ecosystem'|'watchlist'|'about'|'privacy';
const resources=[
 ['Gonka','Protocol documentation, developer guides and network updates.','https://gonka.ai/docs/','PROTOCOL'],
 ['Gonka chain','Inspect the protocol implementation and release history.','https://github.com/gonka-ai/gonka','SOURCE CODE'],
 ['Gonka RPC','Public endpoint reference and machine-readable discovery.','https://rpc.gonka.gg/agents','RPC & AGENTS'],
 ['Feather','Self-hosted chain/RPC infrastructure and an analytics index.','https://github.com/gonkalabs/feather','SELF-HOSTING'],
 ['OpenGNK','An OpenAI-compatible proxy for Gonka inference.','https://github.com/gonkalabs/opengnk','INFERENCE'],
 ['G-Meter','Open-source broker observability and capability probes.','https://github.com/gonkalabs/gmeter','OBSERVABILITY'],
 ['OpenBroker','Managed DevShard access and provider accounting documentation.','https://openbroker.gonka.gg/docs','PROVIDER'],
 ['Proxy','Provider model access, capabilities and published pricing.','https://proxy.gonka.gg/','PROVIDER'],
 ['Pulse','Original media coverage and provider-reported sentiment.','https://pulse.gonka.gg/','COMMUNITY']
] as const;
function Watchlist({s}:{s:Snapshot}){
 const [saved,setSaved]=useState<string[]>([]),[ready,setReady]=useState(false);
 useEffect(()=>{const refresh=()=>{try{const raw:unknown=JSON.parse(localStorage.getItem('gonkastats-watchlist')??'[]');setSaved(Array.isArray(raw)?[...new Set(raw.filter((x):x is string=>typeof x==='string'&&bech32Address(x)))].slice(0,100):[]);}catch{setSaved([]);}setReady(true);};refresh();window.addEventListener('storage',refresh);window.addEventListener('gonkastats-watchlist',refresh);return()=>{window.removeEventListener('storage',refresh);window.removeEventListener('gonkastats-watchlist',refresh);};},[]);
 const rows=saved.map(address=>({address,participant:s.participants.find(p=>p.address===address)}));
 return <Panel title="Your locally saved addresses" description="Stored only in this browser; this is not a portfolio or a hosted alert subscription." footer={<Proof snapshot={s} ids={['participants']}/>}>
 {!ready?<p role="status">Reading local watchlist…</p>:!rows.length?<Empty title="Keep an eye on the compute you care about">Star an address on the <Link className="accent" href="/participants">participants page</Link> to see it here. No login, wallet connection, or signing is needed.</Empty>:<DataTable rows={rows} rowKey={r=>r.address} exportName="watchlist" source={s.sources.find(x=>x.id==='participants')} columns={[
 {key:'address',label:'Address',value:r=>r.address,render:r=><Link className="mono" href={'/participants/'+r.address}>{shorten(r.address,8)}</Link>},
 {key:'weight',label:'Declared weight',value:r=>r.participant?.weight??null,render:r=>format(r.participant?.weight,'number')},
 {key:'status',label:'Observed membership',value:r=>!r.participant?'Not in this observation':r.participant.excluded?'Marked excluded':'Declared member'},
 {key:'watch',label:'Saved',value:r=>r.address,render:r=><Watch address={r.address}/>}
 ]}/>}
 </Panel>;
}
export function Community({s,section}:{s:Snapshot;section:Section}){
 const titles={hardware:'See the hardware behind the numbers',ecosystem:'Find your place in the ecosystem',watchlist:'Your view of the compute collective',about:'Independent by design',privacy:'Understand what stays where'};
 const descriptions={hardware:'Reported GPU registrations matched to declared epoch ML-node IDs. Never inferred from a compute-weight multiplier.',ecosystem:'A source-attributed community directory, not a list of endorsements or verified service guarantees.',watchlist:'Follow public addresses locally, with source-reported membership and exclusions.',about:'GonkaStats is an independent community observatory built by Nosyt Labs.',privacy:'How the application handles public observations, local preferences, and upstream requests.'};
 const hardware=s.sources.some(x=>x.id==='hardware'&&x.status!=='unavailable'),total=s.hardware.reduce((a,x)=>a+x.count,0);
 return <><PageHeading eyebrow={'COMMUNITY / '+section.toUpperCase()} title={titles[section]} description={descriptions[section]} snapshot={s}/>
 {section==='hardware'?<><div className="metric-grid three"><Metric label="Matched GPU registrations" value={hardware?total:null} note="Including registrations of marked exclusions" icon={<Cpu size={18}/>}/><Metric label="Reported hardware categories" value={hardware?s.hardware.length:null} note="Exact source labels, not inferred GPU families" icon={<Layers size={18}/>}/><Metric label="Independent physical audit" value={null} note="Registration does not prove physical inventory" icon={<ShieldCheck size={18}/>}/></div><Panel title="Hardware registration breakdown" description="Search, sort, and export the observed GPU mix." footer={<Proof snapshot={s} ids={['hardware','participants']}/>}>
 {hardware?<DataTable rows={s.hardware} rowKey={r=>r.model} exportName="hardware" source={s.sources.find(x=>x.id==='hardware')} columns={[{key:'model',label:'Reported model / memory',value:r=>r.model},{key:'count',label:'Registered count',value:r=>r.count},{key:'share',label:'Share of matched registrations',value:r=>total?r.count/total*100:null,render:r=>total?format(r.count/total*100,'percent'):'—'}]}/>:<Empty>No usable hardware response was received. Missing inventory is not zero GPUs.</Empty>}</Panel><Panel title="Why there is no invented H100-equivalent count"><p>Declared weight, consensus power, registered GPUs, and physical capacity answer different questions. This page matches participant and ML-node IDs and counts each registration once. It does not infer geography, utilization, hardware uptime, or capacity from a static conversion factor.</p><Link className="button" href="/network">Explore declared compute weight</Link></Panel></>:null}
 {section==='ecosystem'?<><div className="resource-grid">{resources.map(([name,description,url,tag])=><a key={url} className="resource-card" href={url} target="_blank" rel="noopener noreferrer"><BookOpen size={23}/><Badge>{tag}</Badge><h2>{name}</h2><p>{description}</p><span>Open original source <ArrowUpRight size={14}/></span></a>)}</div><Panel title="Build with the community"><p>Feather, OpenGNK and G-Meter are distinct projects, not services silently deployed by this site. Use their own documentation for prerequisites, licensing, security settings and operating costs. Paid probes and wallet operations are not enabled here.</p><External href="https://github.com/NosytLabs/Gonkastats">GonkaStats source repository</External></Panel></>:null}
 {section==='watchlist'?<Watchlist s={s}/>:null}
 {section==='about'?<><Panel title="A useful view, without an affiliation claim"><p>GonkaStats by Nosyt Labs is independent of the Gonka protocol team, Gonka Labs and VeniceStats. Our SVG mark is the GonkaStats product identity, not a claim of official approval.</p><p>The product takes inspiration from the depth of VeniceStats: connected detail pages, clear formulas, useful developer APIs and practical calculators. Gonka-specific compute, epoch and settlement semantics drive the implementation.</p><div className="chip-list"><Link className="button" href="/methodology">Metric definitions</Link><Link className="button" href="/sources">Source health</Link><External href="https://github.com/NosytLabs/Gonkastats">Inspect the code</External></div></Panel><Panel title="What we do not claim"><p>Source-reported figures are not independent audits. A provider conversion quote is not a market trade. Registered hardware is not verified physical inventory. A cost scenario is not a settled bill or a profitability promise.</p><p>Public analytics work without a wallet. Historical storage is optional. Private account connections, paid benchmarking, hosted AI chat and an authorized social-content feed remain separate, disabled integrations.</p></Panel></>:null}
 {section==='privacy'?<><Panel title="Public observations"><p>The application fetches public chain, model, pricing and discovery data on the server. Public addresses in the dataset are blockchain identifiers; they are not labelled as real-world people without attribution. Snapshots may be retained by the operator for analytics and history.</p></Panel><Panel title="Your browser"><p>Color theme and starred addresses use localStorage keys <code>gonkastats-theme</code> and <code>gonkastats-watchlist</code>. The watchlist is not uploaded by this application. Clear those keys or the site’s browser data to remove them.</p><p>CSV/JSON exports are produced in your browser. The application does not include a third-party analytics tracker or a private API-key form. These statements describe this source release, not independently modified deployments.</p></Panel><Panel title="Hosting and external services"><p>Your hosting provider may record requests, network addresses and diagnostics under its own policies. Upstream providers may record requests made by the server. Following an external link takes you to a service with separate policies; this site cannot promise those services have zero logging.</p><p>Public lookups can appear in page URLs, browser history and hosting logs. Do not enter secrets into search, lookup or API-reference fields. No wallet seeds, signing keys or billable model requests are needed for public analytics.</p><External href="https://github.com/NosytLabs/Gonkastats/issues">Project support and implementation questions</External></Panel></>:null}
 </>;
}
