'use client';
import Link from 'next/link';
import {useState} from 'react';
import {BookOpen, Code2, Cpu, Compass, ArrowRight, ArrowUpRight} from 'lucide-react';
import {Panel, Badge, External, CopyButton} from '@/components/ui';
import {PageHeading} from './shared';
import type {Snapshot} from '@/core/types';
const paths = {
 explore:{title:'Understand the network',lead:'Start with the overview, then inspect the source behind one number.',steps:[['Read the dashboard','Separate current observations from long-term history.','/'],['Look at compute','Compare reported GPU registrations and epoch membership.','/network'],['Check the evidence','See the source, timestamps, coverage and any errors.','/sources']]},
 build:{title:'Build with Gonka data or inference',lead:'Reading network statistics and paying for an AI response are different operations.',steps:[['Compare models','Review reported context, output limits and tool support.','/models'],['Estimate cost','Keep advertised rates, retry scenarios and settlement separate.','/cost-lab'],['Inspect the developer API','Try this site’s read-only examples. No wallet key is needed.','/developers']]},
 host:{title:'Research hosting before committing hardware',lead:'Dashboard registrations do not prove that your proposed hardware is eligible or profitable.',steps:[['Inspect reported hardware','See epoch-matched registrations without H100-equivalence guesses.','/hardware'],['Understand epoch changes','Compare reported members and declared weights.','/epoch-diff'],['Inspect reward parameters','Current parameters are not an APY or a profitability promise.','/rewards']]},
} as const;
const terms = [
 ['GNK and ngonka','GNK is the native token unit shown here. One GNK equals 1,000,000,000 ngonka. AI tokens and GNK are different units.'],
 ['Text tokens and Gonka AI Tokens','Prompt and completion tokens measure text processed by a model. Gonka’s official glossary separately defines AI Token as a model-specific unit of compute. Read each source field’s definition before comparing counts; neither is the native GNK coin.'],
 ['Epoch','A protocol-defined operating interval with stages and block boundaries. The dashboard reads those boundaries; its wall-clock countdown is an estimate.'],
 ['Participant and ML node','A participant is a network identity. An ML node is a reported inference deployment within that identity. Neither automatically means one GPU or one company.'],
 ['Declared weight','Weight reported in an epoch membership response. A member’s share uses the same declared-weight denominator. It is not presented as current consensus voting power.'],
 ['GPU registration','Hardware information reported by the source and matched to an epoch’s node IDs. It is not an independent physical audit, uptime test or utilization measurement.'],
 ['Gateway and broker','A gateway handles access to inference infrastructure and sessions. A broker/provider offers an API to customers. Availability, pricing and account data can differ by provider.'],
 ['DevShard and escrow','DevShard inference uses gateway-managed capacity and escrow accounting. Reserving funds is not identical to spending them. Existing escrows can retain creation-time pricing terms.'],
 ['Context and maximum output','Context is the reported working window for a request. Maximum output is a separate limit on the response. Do not assume you can use both limits in full simultaneously.'],
 ['Tool calling and reasoning','Provider-reported capability flags. They do not prove independent benchmark performance, native implementation, or compatibility with every client.'],
 ['Quote, estimate and settlement','A quote is an advertised rate. An estimate applies assumptions to a workload. Settlement is confirmed accounting. These are different stages.'],
 ['Snapshot, stale and unavailable','Snapshot means a retained observation. Stale means the data is old or a later fetch failed. Unavailable means no usable response—not a measured zero.'],
];
const faqs = [
 ['Why do the activity charts not show AI tokens?','They count transactions or gas in returned indexed blocks. Those records are a different population from AI requests and token usage. When the inference source fails, we leave usage unavailable rather than relabel transaction counts.'],
 ['Why is there no GNK market cap?','The connected supply endpoint reports issued native supply, not a verified circulating-supply definition. The displayed conversion reference comes from a provider, not an executed market trade. Multiplying those together would give a misleading market-cap label.'],
 ['Why are some historical charts empty?','Historical series need real stored observations. The application includes an optional collector and database integration, but it never manufactures past points. A range selector cannot create data the operator has not collected.'],
 ['Does “available model” mean the whole network serves it?','No. This catalog describes OpenBroker availability. Capabilities and advertised USD quotes come from Proxy. The source labels keep provider claims separate from network-wide claims.'],
 ['Why can two providers show different prices?','They can use different charging rules, currency conversions, retries and fees. OpenBroker distinguishes estimated usage from confirmed DevShard settlement and describes epoch-level adjustments. Read current terms rather than a screenshot price.'],
 ['Is the retry multiplier a measured network average?','Not in this application. The Cost Lab multiplier is a scenario chosen by you. It does not predict the attempts for a particular request, and it excludes separately listed fees.'],
 ['Do I need a wallet to use GonkaStats?','No. Public dashboard reads, model comparisons and data exports require no wallet connection. The application does not ask for seeds or signing keys and does not run paid inference.'],
 ['Can I use the agent endpoint catalog to send transactions?','The upstream catalog can describe write operations, but GonkaStats only executes its own curated read-only requests. Discovery metadata is not permission to spend funds or broadcast a transaction.'],
];
const example="curl --fail --silent --show-error 'https://api.openbroker.gonka.gg/v1/models'";
export function Learn({s}:{s:Snapshot}){
 const [path,setPath]=useState<keyof typeof paths>('explore');
 return <div className="observatory-v2"><PageHeading eyebrow="THE GONKA FIELD GUIDE" title="More understanding. Less guesswork." description="A practical guide to the network, the model catalog, and the numbers on this site." snapshot={s}/>
 <Panel title="Start with what you want to do" description="Three paths through the same community observatory"><div className="learning-paths" aria-label="Choose a learning path">{(['explore','build','host'] as const).map((key,i)=>{const Icon=[Compass,Code2,Cpu][i];return <button key={key} aria-pressed={path===key} onClick={()=>setPath(key)}><Icon size={18}/>{key==='explore'?'Explore Gonka':key==='build'?'Build something':'Research hosting'}</button>;})}</div><div className="learning-intro"><Badge>START HERE</Badge><h3>{paths[path].title}</h3><p>{paths[path].lead}</p></div><div className="learning-steps">{paths[path].steps.map(([title,body,href],i)=><Link key={href} href={href}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div><ArrowRight size={17}/></Link>)}</div><div className="proof"><External href={path==='host'?'https://gonka.ai/docs/host/quickstart/':'https://gonka.ai/docs/developer/quickstart/'}>Continue with the official {path==='host'?'host':'developer'} guide</External></div></Panel>
 <section id="models" className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">READ A MODEL CARD</div><h2>Compare specifications, not promises.</h2></div><Link className="more" href="/models">Open model explorer <ArrowUpRight size={14}/></Link></div><div className="explainer-grid"><article><BookOpen size={22}/><h3>Context is not answer quality</h3><p>A larger reported context window can accommodate more input. It does not prove the model is more accurate or better at your task.</p></article><article><Cpu size={22}/><h3>VRAM is provider infrastructure</h3><p>The deployment VRAM field is not a requirement for your laptop when you call a hosted API.</p></article><article><Code2 size={22}/><h3>Capabilities need client testing</h3><p>Reported tool calling or reasoning support is metadata. Check the provider’s integration guide for your client.</p></article></div></section>
 <Panel title="A safe first API request" description="Read the public model list. This does not generate an AI response or spend tokens."><pre className="code-sample">{example}</pre><CopyButton text={example} label="Copy public models request"/><div className="proof"><External href="https://openbroker.gonka.gg/docs">OpenBroker API and accounting docs</External><External href="https://rpc.gonka.gg/agents">Gonka RPC agent discovery</External></div></Panel>
 <section id="openbroker" className="dashboard-section"><Panel title="OpenBroker: read the bill, not just the headline rate" description="Provider documentation reviewed 2026-09-21; public catalog reads and private account reads are different."><div className="accounting-guide"><article><Badge>01 / DISCOVER</Badge><h3>Choose a current model</h3><code>GET /v1/models</code><p>The API host is api.openbroker.gonka.gg. Its public catalog does not require a key. Do not use a model ID copied from an old screenshot.</p></article><article><Badge>02 / BUDGET</Badge><h3>Check fit and price separately</h3><p>Use reported context and output limits, then calculate a workload scenario. Escrow parameters can be fixed at creation; today’s price does not rewrite historical costs.</p><Link className="more" href="/workload">Plan context <ArrowUpRight size={14}/></Link></article><article><Badge>03 / RECONCILE</Badge><h3>Inspect cost_source</h3><p>OpenBroker documents estimated rows, gateway-confirmed settlement and separate epoch escrow adjustments. An estimate must not be relabelled as a settled bill.</p></article></div><div className="table-scroll"><table><caption className="sr-only">OpenBroker account endpoint distinctions</caption><thead><tr><th>Question</th><th>Documented endpoint</th><th>Important boundary</th></tr></thead><tbody><tr><td>What can my account spend?</td><td><code>GET /v1/balance</code></td><td>Available balance differs from total balance after reservations. Authentication required.</td></tr><tr><td>What did this date range cost?</td><td><code>GET /v1/usage/summary</code></td><td>Period/model aggregates; documentation specifies a maximum 90-day range and excludes synthetic escrow lines.</td></tr><tr><td>What happened to one request?</td><td><code>GET /v1/usage/&#123;id&#125;</code></td><td>Inspect cost_source and request/response IDs. The paginated usage list’s accompanying totals are lifetime, not date-filter totals.</td></tr></tbody></table></div><p className="chart-explainer">These are documented provider APIs, not private integrations enabled on GonkaStats. No key is collected, no deposit is initiated, and no paid completion is sent here.</p><External href="https://openbroker.gonka.gg/docs">Read the original OpenBroker documentation</External></Panel></section>
 <section id="glossary" className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">THE NUMBERS, DECODED</div><h2>A plain-language glossary.</h2></div><External href="https://gonka.ai/docs/glossary/">Official glossary</External></div><dl className="glossary-grid">{terms.map(([term,description])=><div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl></section>
 <Panel title="Questions worth asking" description="What the data can—and cannot—tell you"><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></Panel>
 <Panel title="Read the original sources"><div className="chip-list"><External href="https://gonka.ai/docs/architecture/">Protocol architecture</External><External href="https://gonka.ai/docs/host/hardware-specifications/">Hardware specifications</External><External href="https://openbroker.gonka.gg/docs#pricing">Provider pricing and cost sources</External><External href="https://gonka.ai/docs/dashboard-maintainer-memo-v0.2.15/">API compatibility memo</External><Link className="more" href="/methodology">Our metric definitions</Link></div><p className="small muted">Educational content reviewed 2026-09-21. Protocol and provider behavior can change; use current upstream documentation for operations.</p></Panel></div>;
}
