'use client';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Box, Search, Columns3, LayoutGrid, List, Download, X, ArrowUpRight, Check} from 'lucide-react';
import {Panel, Proof, Badge, Empty, CopyButton, download} from '@/components/ui';
import {ModelComparisonChart, ModelFootprintChart} from '@/components/insight-charts';
import {readModelFilters, filterModels, modelFootprint, hasObservation} from '@/core/insights';
import {csv, format} from '@/core/metrics';
import type {Snapshot, Model} from '@/core/types';
import {PageHeading, ObservationBar} from './shared';
const capability = (value: boolean | null) => value === null ? 'Unknown' : value ? 'Reported supported' : 'Not reported supported';
export function ModelExplorer({s}: {s: Snapshot}) {
  const search = useSearchParams(), filters = readModelFilters(new URLSearchParams(search.toString()));
  const rows = filterModels(s.models, filters), selected = s.models.filter(m => filters.compare.includes(m.slug));
  const footprint = new Map(modelFootprint(s).map(row => [row.model, row.count]));
  function update(key: string, values: string[]) {
    const params = new URLSearchParams(search.toString()); params.delete(key);
    for (const value of values) if (value) params.append(key, value);
    window.history.replaceState(null, '', '/models' + (params.size ? '?' + params.toString() : ''));
  }
  function compare(m: Model) {update('compare', filters.compare.includes(m.slug) ? filters.compare.filter(slug => slug !== m.slug) : [...filters.compare, m.slug].slice(0, 3));}
  const reset = () => window.history.replaceState(null, '', '/models');
  return <div className="observatory-v2"><PageHeading eyebrow="MODEL EXPLORER / CATALOG, NOT A LEADERBOARD" title="Find your next model" description="Compare reported context, tool support, participation and price. No made-up quality scores." snapshot={s}/><ObservationBar s={s}/>
    <div className="model-topline"><div><Box size={19}/><strong>{hasObservation(s, 'models') ? s.models.length : '—'}</strong> available in OpenBroker’s catalog</div><Link href="/learn#models">What do these specifications mean? <ArrowUpRight size={14}/></Link></div>
    <Panel title="Explore the catalog" description="Filters and selected comparisons stay in the URL so you can share this view.">
      <div className="model-toolbar"><label className="search-field"><Search size={16}/><input aria-label="Search model catalog" placeholder="Search model name or ID…" value={filters.q} onChange={e => update('q', [e.target.value])}/></label>
        <label className="filter-control">Capability<select value={filters.capability} onChange={e => update('capability', [e.target.value])}><option value="all">All capabilities</option><option value="tools">Tool calling</option><option value="reasoning">Reasoning</option><option value="long-context">128K+ context</option></select></label>
        <label className="filter-control">Sort by<select value={filters.sort} onChange={e => update('sort', [e.target.value])}><option value="name">Name</option><option value="context">Largest context</option><option value="price">Lowest quoted price</option></select></label>
        <div className="segmented" aria-label="Model catalog view"><button aria-label="Model cards" aria-pressed={filters.view === 'cards'} onClick={() => update('view', ['cards'])}><LayoutGrid size={16}/></button><button aria-label="Model table" aria-pressed={filters.view === 'table'} onClick={() => update('view', ['table'])}><List size={16}/></button></div>
      </div><div className="filter-summary"><span role="status">{rows.length} of {s.models.length} models · unknown capabilities do not match capability filters</span><button className="text-button" onClick={reset}>Reset filters</button><button className="button ghost compact" onClick={() => download('gonka-models.csv', csv(rows.map(m => ({model: m.id, context_tokens: m.context, max_output_tokens: m.output, tools: m.tools, reasoning: m.reasoning, proxy_usd_per_million_tokens: m.price, declared_members: footprint.get(m.id), catalog_source: s.sources.find(x => x.id === 'models')?.url, capability_source_time: s.sources.find(x => x.id === 'capabilities')?.sourceTime, price_fetched_at: s.sources.find(x => x.id === 'pricing')?.fetchedAt}))), 'text/csv')}><Download size={14}/> Export filtered</button></div>
      {!rows.length ? <Empty title="No models match this view">Try another name or clear the capability filter. No matches does not mean the network has no models.</Empty> : filters.view === 'table' ? <div className="table-scroll"><table><caption className="sr-only">Filtered Gonka model catalog</caption><thead><tr><th>Model</th><th>Context tokens</th><th>Max output</th><th>Tools</th><th>Reasoning</th><th>Proxy quote / 1M</th><th>Compare</th></tr></thead><tbody>{rows.map(m => <tr key={m.id}><td><Link href={'/models/' + m.slug}>{m.name}</Link></td><td>{format(m.context, 'number')}</td><td>{format(m.output, 'number')}</td><td>{capability(m.tools)}</td><td>{capability(m.reasoning)}</td><td title={m.price ?? 'Unavailable'}>{format(m.price, 'usd')}</td><td><button className="button compact" aria-label={'Compare ' + m.name} aria-pressed={filters.compare.includes(m.slug)} disabled={selected.length === 3 && !filters.compare.includes(m.slug)} onClick={() => compare(m)}>{filters.compare.includes(m.slug) ? 'Selected' : 'Compare'}</button></td></tr>)}</tbody></table></div> : <div className="model-catalog-cards">{rows.map((m, i) => <article className="catalog-card" key={m.id}><header><span className={'model-icon model-' + i}><Box size={20}/></span><Badge>OPENBROKER CATALOG</Badge></header><h3><Link href={'/models/' + m.slug}>{m.name}</Link></h3><code className="model-id">{m.id}</code><div className="catalog-price"><strong title={m.price ?? 'Unavailable'}>{format(m.price, 'usd')}</strong><span>Proxy quote / 1M tokens</span></div><dl className="model-specs"><div><dt>Context window</dt><dd>{format(m.context)} tokens</dd></div><div><dt>Maximum output</dt><dd>{format(m.output)} tokens</dd></div><div><dt>Members reporting support</dt><dd>{footprint.get(m.id) ?? '—'}</dd></div></dl><div className="capability-pills"><Badge tone={m.tools ? 'green' : 'muted'}>Tools: {m.tools === null ? 'unknown' : m.tools ? 'yes*' : 'no*'}</Badge><Badge tone={m.reasoning ? 'blue' : 'muted'}>Reasoning: {m.reasoning === null ? 'unknown' : m.reasoning ? 'yes*' : 'no*'}</Badge></div><footer><Link href={'/models/' + m.slug} className="more">Model details <ArrowUpRight size={14}/></Link><button className="button compact" aria-label={'Compare ' + m.name} aria-pressed={filters.compare.includes(m.slug)} disabled={selected.length === 3 && !filters.compare.includes(m.slug)} onClick={() => compare(m)}>{filters.compare.includes(m.slug) ? <Check size={13}/> : <Columns3 size={13}/>} {filters.compare.includes(m.slug) ? 'Selected' : 'Compare'}</button></footer></article>)}</div>}
      <p className="chart-explainer">*Capability flags are provider-reported metadata, not independent tests. Model participation counts overlap; they are not market share or usage volume. Prices are never rounded down to a misleading “free” label.</p><Proof snapshot={s} ids={['models', 'capabilities', 'pricing', 'participants']}/>
    </Panel>
    <section id="compare" aria-label="Selected model comparison"><Panel title={'Side-by-side comparison' + (selected.length ? ' · ' + selected.length + '/3' : '')} description="Select up to three models above. The comparison stays visible even when you filter the catalog." action={selected.length ? <button className="button ghost compact" onClick={() => update('compare', [])}><X size={13}/> Clear comparison</button> : undefined}>
      {!selected.length ? <div className="compare-empty"><Columns3 size={24}/><p>Choose <strong>Compare</strong> on a model card to line up the specifications.</p></div> : <><div className="table-scroll"><table className="model-comparison-table"><caption className="sr-only">Selected models compared on reported specifications</caption><thead><tr><th>Specification</th>{selected.map(m => <th key={m.id}><Link href={'/models/' + m.slug}>{m.name}</Link></th>)}</tr></thead><tbody>{([
        ['Context window', (m: Model) => format(m.context, 'number') + ' tokens'],
        ['Maximum output', (m: Model) => format(m.output, 'number') + ' tokens'],
        ['Tool calling', (m: Model) => capability(m.tools)], ['Reasoning', (m: Model) => capability(m.reasoning)],
        ['Proxy quote / 1M tokens', (m: Model) => format(m.price, 'usd')],
        ['Members reporting support', (m: Model) => String(footprint.get(m.id) ?? 'Unknown')],
        ['Reported deployment VRAM', (m: Model) => format(m.vram, 'number') + ' GB'],
      ] as [string, (model: Model) => string][]).map(([name, render]) => <tr key={name}><th scope="row">{name}</th>{selected.map(m => <td key={m.id}>{render(m)}</td>)}</tr>)}</tbody></table></div><p className="chart-explainer">Deployment VRAM describes provider infrastructure, not the device you need to call an API. These figures do not establish which model is “best.”</p><CopyButton text={'/models?' + search.toString()} label="Copy comparison path"/></>}
    </Panel></section><div className="grid-two"><ModelComparisonChart s={s}/><ModelFootprintChart s={s}/></div><div className="reader-note"><Box size={18}/><div><strong>Ready to try a model?</strong> Estimate a realistic workload before choosing a provider.</div><Link href="/cost-lab">Open Cost Lab <ArrowUpRight size={14}/></Link></div>
  </div>;
}
