'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {Coins,Users,Cpu,Box,Wallet,Layers,ArrowUpRight,BookOpen,ArrowRight,Terminal,Activity} from 'lucide-react';
import {Panel,Proof,More,Metric,Badge,SourceNote} from '@/components/ui';
import {overviewFacts,hasObservation} from '@/core/insights';
import {format} from '@/core/metrics';
import type {Snapshot} from '@/core/types';
import {ObservationBar,PageHeading,EpochTimeline,ParticipantsTable,ModelsList,ProposalList} from './shared';
import {GovernanceChart} from '@/components/composition-charts';
import {HardwareChart,ModelFootprintChart,ConcentrationChart,ModelComparisonChart} from '@/components/insight-charts';
const ActivityChart=dynamic(()=>import('@/components/charts').then(m=>m.ActivityChart),{loading:()=> <div className="chart-placeholder">Preparing observed block activity…</div>});
export function Overview({s}:{s:Snapshot}){
 const facts=overviewFacts(s);
 const cards=[
 {label:'GNK reference',value:hasObservation(s,'pricing')?s.fx:null,kind:'usd' as const,note:'Provider conversion · not a market trade',icon:Coins,source:'pricing'},
 {label:'Epoch members',value:facts.members,kind:'number' as const,note:`${facts.excluded??'Unknown'} marked excluded · not an uptime count`,icon:Users,source:'participants'},
 {label:'GPU registrations',value:facts.gpus,kind:'compact' as const,note:'Matched to epoch ML nodes · reported',icon:Cpu,source:'hardware'},
 {label:'Available models',value:facts.models,kind:'number' as const,note:'OpenBroker catalog · provider scope',icon:Box,source:'models'},
 {label:'Native issued supply',value:hasObservation(s,'supply')?s.totalSupply:null,kind:'compact' as const,note:'GNK · not circulating supply',icon:Layers,source:'supply'},
 {label:'Community pool',value:hasObservation(s,'community')?s.communityPool:null,kind:'compact' as const,note:'GNK · distribution module only',icon:Wallet,source:'community'}];
 return <div className="observatory-v2"><PageHeading eyebrow="INDEPENDENT GONKA COMMUNITY ANALYTICS" title="Gonka, at a glance" description="Understand the compute. Compare the models. See where every number comes from." snapshot={s}/><ObservationBar s={s}/><nav className="section-nav" aria-label="Dashboard sections"><a href="#network-activity">Activity</a><a href="#compute">Compute</a><a href="#models">Models</a><a href="#community">Community</a><Link href="/learn"><BookOpen size={14}/> Start here</Link></nav>
 <div className="dashboard-kpis">{cards.map(card=><div className="kpi-tile" key={card.label}><Metric label={card.label} value={card.value} kind={card.kind} note={card.note} icon={<card.icon size={18}/>} accent={card.source==='pricing'}/><SourceNote source={s.sources.find(x=>x.id===card.source)}/></div>)}</div><div className="reader-note"><BookOpen size={18}/><div><strong>New to Gonka?</strong> It helps to separate the network, the provider, and your bill.</div><Link href="/learn">Read the field guide <ArrowUpRight size={14}/></Link></div>
 <section id="network-activity" className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">01 / NETWORK ACTIVITY</div><h2>What is happening on-chain?</h2></div><More href="/blocks">Open explorer</More></div><div className="grid-main"><Panel title="Transactions in observed blocks" description="Change the record count or measure. Blockchain activity is not AI request volume." action={<Badge><Activity size={12}/> INDEXED DATA</Badge>} footer={<Proof snapshot={s} ids={['blocks']}/>}><ActivityChart blocks={s.blocks}/></Panel><Panel title="Where are we in this epoch?" description="The network’s current operating interval" footer={<Proof snapshot={s} ids={['epoch','blocks']}/>}><EpochTimeline s={s}/><div className="epoch-detail-link"><Link href="/epochs">Explore stages and parameters <ArrowRight size={14}/></Link></div></Panel></div></section>
 <section id="compute" className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">02 / THE COMPUTE COLLECTIVE</div><h2>Hardware and participation, explained.</h2></div><More href="/network">Network details</More></div><div className="context-strip"><div><span>Declared epoch weight</span><strong>{format(facts.weight)}</strong><small>Not current consensus power</small></div><div><span>Reported ML nodes</span><strong>{format(facts.nodes)}</strong><small>Unique IDs within each member</small></div><div><span>Members not marked excluded</span><strong>{format(facts.notExcluded)}</strong><small>Not a service-health guarantee</small></div></div><div className="grid-two"><HardwareChart s={s}/><ConcentrationChart s={s}/></div><Panel title="Largest declared members" description="Explore weight, model support, and separately reported exclusions" action={<More href="/participants">All members</More>} footer={<Proof snapshot={s} ids={['participants']}/>}><ParticipantsTable s={s} compact/></Panel></section>
 <section id="models" className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">03 / MODELS & ACCESS</div><h2>Find the right model for your workload.</h2></div><More href="/models">Model explorer</More></div><div className="grid-two"><ModelComparisonChart s={s}/><ModelFootprintChart s={s}/></div><div className="reader-note"><Box size={18}/><div><strong>Will the whole request fit?</strong> Budget your input plus response reserve against reported model limits.</div><Link href="/workload">Plan the context <ArrowUpRight size={14}/></Link></div><Panel title="Available through OpenBroker" description="Capability metadata and published quotes are separately attributed" action={<More href="/cost-lab">Estimate a workload</More>} footer={<Proof snapshot={s} ids={['models','capabilities','pricing']}/>}><ModelsList s={s}/></Panel>{!hasObservation(s,'stats')&&<div className="reader-note data-gap"><Activity size={18}/><div><strong>AI usage totals are unavailable.</strong> The inference statistics source did not return a usable dataset. Block transactions are not substituted for requests or tokens.</div><Link href="/inference">View coverage <ArrowUpRight size={14}/></Link></div>}</section>
 <section id="community" className="dashboard-section"><div className="section-heading"><div><div className="eyebrow">04 / YOUR COMMUNITY WORKSPACE</div><h2>Go from a number to an answer.</h2></div></div><div className="insight-grid"><Link className="insight" href="/cost-lab"><div className="insight-icon"><Coins size={20}/></div><Badge>CALCULATE</Badge><h3>What will this workload cost?</h3><p>Compare an advertised quote, a single execution and a retry-inclusive scenario.</p><span>Open Cost Lab <ArrowUpRight size={14}/></span></Link><Link className="insight" href="/epoch-diff"><div className="insight-icon purple"><Layers size={20}/></div><Badge>COMPARE</Badge><h3>What changed between epochs?</h3><p>Inspect joining and departing members and changes in their declared weight.</p><span>Compare epochs <ArrowUpRight size={14}/></span></Link><Link className="insight" href="/learn"><div className="insight-icon amber"><BookOpen size={20}/></div><Badge>LEARN</Badge><h3>Make sense of the terminology.</h3><p>Tokens, context, GPU registrations and settlement—in plain language.</p><span>Read the Gonka field guide <ArrowUpRight size={14}/></span></Link></div><div className="grid-two"><GovernanceChart s={s}/><Panel title="Protocol decisions" description="Recently returned governance proposals" action={<More href="/governance"/>} footer={<Proof snapshot={s} ids={['governance']}/>}><ProposalList s={s} compact/></Panel></div></section>
 <section className="agent-banner"><div className="agent-art" aria-hidden="true"><Terminal size={32}/></div><div><div className="eyebrow">OPEN DATA. CLEAR BOUNDARIES.</div><h2>The same observations, for your tools.</h2><p>Read-only APIs, source timestamps, an interactive reference and Gonka RPC discovery.</p></div><Link className="button primary" href="/agents">Agent workbench <ArrowUpRight size={15}/></Link></section></div>;
}
