'use client';
import dynamic from 'next/dynamic';
import {Coins,Users,Network,Box,ArrowUpRight,Terminal,Layers,ShieldCheck,Activity} from 'lucide-react';
import Link from 'next/link';
import {Panel,Proof,More,Metric,Badge} from '@/components/ui';
import {sum,format} from '@/core/metrics';
import type {Snapshot} from '@/core/types';
import {ObservationBar,PageHeading,EpochTimeline,ParticipantsTable,ModelsList,ProposalList,BlocksTable} from './shared';
const ActivityChart=dynamic(()=>import('@/components/charts').then(m=>m.ActivityChart),{loading:()=> <div className="chart-placeholder">Preparing indexed activity…</div>});
const WeightChart=dynamic(()=>import('@/components/charts').then(m=>m.WeightChart),{loading:()=> <div className="chart-placeholder"/>});
export function Overview({s}:{s:Snapshot}){const excluded=s.participants.filter(p=>p.excluded).length,weight=s.participants.length?sum(s.participants.map(p=>p.weight)):null;return <><PageHeading eyebrow="THE GONKA OBSERVATORY" title="A clearer view of the network" description="Compute, inference, and the economics underneath. Every number, traceable." snapshot={s}/><ObservationBar s={s}/><div className="metric-grid"><Metric label="GNK conversion reference" value={s.fx} kind="usd" note="Proxy reference · not an executed trade" icon={<Coins size={17}/>} accent/><Metric label="Epoch members" value={s.participants.length||null} note={s.participants.length?excluded+' currently marked excluded':'Source unavailable'} icon={<Users size={17}/>}/><Metric label="Declared epoch weight" value={weight} note="Membership snapshot · not consensus power" icon={<Network size={17}/>}/><Metric label="Available models" value={s.models.length||null} note="OpenBroker reported catalog" icon={<Box size={17}/>}/></div><div className="metric-provenance"><Proof snapshot={s} ids={['pricing','participants','models']}/></div>
<div className="grid-main"><Panel title="The network, in motion" description="Transaction activity across the latest indexed blocks" action={<Badge tone="green"><Activity size={11}/> CHAIN ACTIVITY</Badge>} footer={<Proof snapshot={s} ids={['blocks']}/>}><ActivityChart blocks={s.blocks}/></Panel><Panel title="Who powers the network" description="Share of declared epoch weight" action={<More href="/network">Explore</More>} footer={<Proof snapshot={s} ids={['participants']}/>}><WeightChart participants={s.participants}/></Panel></div>
<div className="grid-two"><Panel title="The epoch clock" action={<More href="/epochs"/>} footer={<Proof snapshot={s} ids={['epoch']}/>}><EpochTimeline s={s}/></Panel><Panel title="Intelligence on tap" description="Provider-reported model availability and prices" action={<More href="/models">All models</More>} footer={<Proof snapshot={s} ids={['models','capabilities','pricing']}/>}><ModelsList s={s}/></Panel></div>
<div className="section-heading"><div><div className="eyebrow">LOOK BENEATH THE HEADLINES</div><h2>Make the network make sense.</h2></div><Link href="/signals" className="more">Open signal desk <ArrowUpRight size={14}/></Link></div><div className="insight-grid"><Link className="insight" href="/cost-lab"><div className="insight-icon"><Coins size={19}/></div><Badge>INTERACTIVE</Badge><h3>The real cost of a million tokens</h3><p>Separate the advertised price, a single execution, and retry-inclusive scenarios.</p><span>Open cost lab <ArrowUpRight size={14}/></span></Link><Link className="insight" href="/epoch-diff"><div className="insight-icon purple"><Layers size={19}/></div><Badge>COMPARE</Badge><h3>What changed between epochs?</h3><p>Trace membership changes and weight deltas with side-by-side chain observations.</p><span>Compare epochs <ArrowUpRight size={14}/></span></Link><Link className="insight" href="/sources"><div className="insight-icon amber"><ShieldCheck size={19}/></div><Badge>PROVENANCE</Badge><h3>Trust the source, not the gloss</h3><p>{s.sources.filter(x=>x.status==='unavailable').length} unavailable sources in this observation. Inspect freshness, coverage, and errors.</p><span>Inspect data sources <ArrowUpRight size={14}/></span></Link></div>
<Panel title="The compute collective" description="Largest members by declared epoch weight" action={<More href="/participants">All participants</More>} className="wide-panel" footer={<Proof snapshot={s} ids={['participants']}/>}><ParticipantsTable s={s} compact/></Panel><div className="grid-two"><Panel title="Recent indexed blocks" action={<More href="/blocks">Open explorer</More>} footer={<Proof snapshot={s} ids={['blocks']}/>}><BlocksTable s={s} compact/></Panel><Panel title="Protocol decisions" description="Recently returned governance proposals" action={<More href="/governance"/>} footer={<Proof snapshot={s} ids={['governance']}/>}><ProposalList s={s} compact/></Panel></div>
<section className="agent-banner"><div className="agent-art" aria-hidden="true"><Terminal size={36}/></div><div><div className="eyebrow">BUILT FOR HUMANS. READABLE BY AGENTS.</div><h2>Give your agent a view of Gonka.</h2><p>A searchable RPC catalog, read-only examples, and the same source-aware API that powers this dashboard.</p></div><Link className="button primary" href="/agents">Agent workbench <ArrowUpRight size={15}/></Link></section><div className="bottom-facts"><span>Issued native supply <strong>{format(s.totalSupply)} GNK</strong></span><span>Current epoch <strong>#{s.epoch?.id??'—'}</strong></span><span>Matched GPU registrations <strong>{s.hardware.length?format(s.hardware.reduce((a,h)=>a+h.count,0)):'—'}</strong></span></div></>;}
