'use client';
import Link from 'next/link';
import {AlertTriangle,ArrowUpRight,Radio,BookOpen,Code2,GitBranch,Activity,Layers,Database} from 'lucide-react';
import {Panel,Proof,Metric,Badge,SourceNote,DataTable,Empty,External} from '@/components/ui';
import type {Snapshot} from '@/core/types';
import {sourceDependents} from '@/core/source-dependencies';
import {PageHeading,MembershipUnavailable} from './shared';
import {hasObservation,overviewFacts} from '@/core/insights';
import {ApiReference} from './api-reference';
export function Sources({s}:{s:Snapshot}){return <><PageHeading eyebrow="PROVENANCE / SOURCE RADAR" title="Every number has a source" description="Fetch success, source age, and coverage are different things. Inspect all three." snapshot={s}/><div className="metric-grid three"><Metric label="Recently fetched" value={s.sources.filter(x=>x.status==='recent').length} note="Not an independently verified correctness score" icon={<Activity size={17}/>}/><Metric label="Retained / stale" value={s.sources.filter(x=>x.status==='stale'||x.status==='snapshot').length} note="Original observation times remain visible" icon={<Database size={17}/>}/><Metric label="Unavailable" value={s.sources.filter(x=>x.status==='unavailable').length} note="No metric substituted with zero" icon={<AlertTriangle size={17}/>}/></div><Panel title="Source health and coverage" description="A successful read is not a service uptime percentage"><DataTable rows={s.sources} rowKey={r=>r.id} exportName="sources" columns={[{key:'name',label:'Source',value:r=>r.name,render:r=><SourceNote source={r}/>},{key:'scope',label:'Scope',value:r=>r.scope,render:r=><Badge>{r.scope}</Badge>},{key:'status',label:'Status',value:r=>r.status,render:r=><Badge tone={r.status==='recent'?'green':r.status==='unavailable'?'red':'amber'}>{r.status}</Badge>},{key:'usedBy',label:'Used by',value:r=>sourceDependents(r.id).join(' '),render:r=>{const routes=sourceDependents(r.id);return routes.length?<div className="chip-list">{routes.map(path=><Link key={path} href={path}>{path}</Link>)}</div>:<span className="muted small">Shared provenance / direct inspection</span>;}},{key:'ttl',label:'TTL',value:r=>r.ttl,render:r=><span className="mono small">{r.ttl}s</span>},{key:'time',label:'Fetched (UTC)',value:r=>r.fetchedAt,render:r=><span className="mono small">{r.fetchedAt.slice(5,19).replace('T',' ')}</span>},{key:'error',label:'Error / coverage',value:r=>r.error??r.coverage,render:r=><span className={'small '+(r.error?'warning-text':'muted')}>{r.error??r.coverage}</span>}]}/></Panel><div className="grid-two"><Panel title="An honest observation model"><p><b>Recent:</b> recently fetched within the configured freshness window.</p><p><b>Stale:</b> retained data whose source time is old or whose latest fetch failed.</p><p><b>Snapshot:</b> an explicitly retained observation, with live refresh disabled.</p><p><b>Unavailable:</b> no usable source response. A dash means unknown, not zero.</p></Panel><Panel title="Collection, not scraping per visitor"><p>Public core reads share a two-minute process cache. With PostgreSQL configured, web requests read stored observations and a separately operated collector performs upstream reads.</p><p>Source reads have bounded concurrency, payload sizes and timeouts. No scheduled GitHub Actions or billable inference health checks are used.</p><Link href="/developers" className="more">Read operational notes <ArrowUpRight size={14}/></Link></Panel></div></>;}
export function Signals({s}:{s:Snapshot}){
 const facts=overviewFacts(s),failed=s.sources.filter(source=>source.status==='unavailable'),stale=s.sources.filter(source=>source.status==='stale');
 const tokenPrice=hasObservation(s,'params')?s.protocol['devshard_escrow_params.token_price']??null:null;
 return <><PageHeading eyebrow="GONKASTATS / SIGNAL DESK" title="Less noise. More context." description="Deterministic observations with inspectable evidence—not an AI-generated market narrative." snapshot={s}/>
 <div className="signal-list">
  <Panel title="Membership and eligibility are not the same" action={<Badge tone="amber">EPOCH STRUCTURE</Badge>} footer={<Proof snapshot={s} ids={['participants']}/>}>
   {facts.members===null?<MembershipUnavailable/>:<><p className="signal-number">{facts.excluded} <span>members marked excluded</span></p><p>{`The returned epoch contains ${facts.members} declared members.`} Exclusions remain visible; neither membership nor a lack of exclusions is an uptime measurement.</p></>}
   <Link href="/participants" className="more">Inspect member statuses <ArrowUpRight size={14}/></Link>
  </Panel>
  <Panel title="Availability does not equal complete coverage" action={<Badge tone={failed.length?'amber':'green'}>SOURCE HEALTH</Badge>}>
   <p className="signal-number">{failed.length} <span>unavailable · {stale.length} stale sources</span></p>
   <p>{!s.sources.length?'No source observations are available.':failed.length?failed.map(source=>source.name).join(', '):'No unavailable sources in this retained observation.'}</p>
   <Link href="/sources" className="more">Inspect source radar <ArrowUpRight size={14}/></Link>
  </Panel>
  <Panel title="Quoted pricing is not a settled bill" action={<Badge tone="blue">COST PROVENANCE</Badge>} footer={<Proof snapshot={s} ids={['pricing','params']}/>}>
   {tokenPrice===null?<Empty title="Escrow pricing unavailable">No usable token-price parameter is available. A provider quote is not substituted for the chain parameter.</Empty>:<p>The retained escrow parameter is <strong>{tokenPrice} ngonka per token per attempt</strong>. Historical escrows may have different recorded terms.</p>}
   <p>A provider quote and a retry scenario are not confirmed settlement.</p><Link href="/cost-lab" className="more">Explore the accounting <ArrowUpRight size={14}/></Link>
  </Panel>
  <Panel title="The catalog contains both reads and writes" action={<Badge>AGENT SAFETY</Badge>} footer={<Proof snapshot={s} ids={['catalog']}/>}>
   {hasObservation(s,'catalog')?<p>{`${s.endpoints.length} endpoint definitions are imported.`} This site executes only its own curated reads; discovery never authorizes a transaction.</p>:<Empty title="Discovery catalog unavailable">No usable endpoint catalog was observed. An unavailable feed is not an empty network API.</Empty>}
   <Link href="/agents" className="more">Explore the read-only workbench <ArrowUpRight size={14}/></Link>
  </Panel>
 </div></>;
}
export function Pulse({s}:{s:Snapshot}){const links=[['Pulse by gonka.gg','Media coverage and provider-reported sentiment','https://pulse.gonka.gg/',Radio],['Official network updates','Protocol changes and maintainer announcements','https://gonka.ai/docs/network-updates/',BookOpen],['Gonka protocol source','Inspect source code, releases, and changes','https://github.com/gonka-ai/gonka',GitBranch],['Feather','Self-operated RPC and analytics infrastructure','https://github.com/gonkalabs/feather',Database],['Gonka developer guide','Understand gateways and the inference flow','https://gonka.ai/docs/developer/quickstart/',Code2],['OpenBroker documentation','Provider-side billing and request accounting','https://openbroker.gonka.gg/docs',Layers]] as const;return <><PageHeading eyebrow="ECOSYSTEM / PULSE" title="Follow the conversation" description="A source-first reading room for the Gonka ecosystem. Original links, clear attribution, no invented sentiment." snapshot={s}/><div className="resource-grid">{links.map(([name,desc,url,Icon])=><a key={name} href={url} className="resource-card" target="_blank" rel="noopener noreferrer"><Icon size={24}/><h2>{name}</h2><p>{desc}</p><span>View original <ArrowUpRight size={14}/></span></a>)}</div><Panel title="Why there is no sentiment score here"><p>A supported public Pulse feed and its sentiment methodology have not been verified for this implementation. We link to the original service rather than fabricate scores, creator reach, topic percentages, or a historical feed.</p><p>When a licensed feed is connected, indexed coverage, sample size, model version, duplicate handling and source timestamps must accompany any sentiment analysis. Social reach is not automatically a count of unique people.</p><Badge tone="amber">AUTOMATED MEDIA FEED NOT CONFIGURED</Badge></Panel></>;}
export function Documentation({s,section}:{s:Snapshot;section:string}){if(section==='developers')return <ApiReference s={s}/>;if(section==='intelligence'||section==='account')return <><PageHeading eyebrow="OPTIONAL INTEGRATION" title={section==='account'?'Your account stays yours':'Intelligence grounded in evidence'} description="This optional integration is not enabled. Public analytics require no sign-in or spending key." snapshot={s}/><Panel title="Not configured"><Empty>Private account analytics and hosted AI chat need separate authorization, authentication, secure credential handling, and explicit spending limits. This build does not solicit API keys or pretend a demo chat is real.</Empty><Link href="/signals" className="button primary">Explore the working signal desk</Link></Panel></>;
if(section==='changelog')return <><PageHeading eyebrow="PRODUCT / CHANGELOG" title="Built in the open" description="Verified repository changes, with the original pull requests. Repository releases are not deployment announcements." snapshot={s}/>
 <div className="grid-two">{[
  {pr:17,title:'Reliable API responses',summary:'Typed lookup failures, cross-origin conditional reads, error-cache fixes, source-consumer coverage and corrected DEX percentage units.'},
  {pr:16,title:'Membership and watchlist cleanup',summary:'Distinct unavailable and observed-empty states, synchronized saved addresses, epoch-matched hardware invalidation and compact Network cards.'},
  {pr:15,title:'Source dialogs and search visibility',summary:'Keyboard-accessible provenance dialogs, readable model metadata, canonical URLs, sitemap coverage and safe malformed-route handling.'},
 ].map(release=><Panel key={release.pr} title={release.title} description="Merged · 3 October 2026"><p>{release.summary}</p><External href={'https://github.com/NosytLabs/Gonkastats/pull/'+release.pr}>Inspect PR #{release.pr}</External></Panel>)}</div>
 <Panel title="What this record does not claim"><p>Source availability changes between observations. These releases do not establish historical coverage, measured provider benchmarks, an authorized social feed or a public deployment.</p><Link href="/sources" className="button">Inspect this observation</Link></Panel></>;
return <><PageHeading eyebrow="PROVENANCE / METHODOLOGY" title="Show the working" description="Definitions, denominators and limitations. Nothing hidden behind a shiny chart." snapshot={s}/><><Panel title="Metric dictionary"><DataTable rows={[
{name:'GNK conversion reference',formula:'Provider-supplied gonka_usd',limits:'Not an executed trade or an independently constructed market index.'},
{name:'Declared epoch weight',formula:'Sum of returned participant.weight values',limits:'Includes separately marked exclusions; not the consensus validator set.'},
{name:'Member share',formula:'Member declared weight / total declared epoch weight',limits:'Same source and epoch denominator. Zero total means unavailable.'},
{name:'Reported ML nodes',formula:'Unique node_id per participant, across returned model groups',limits:'Missing field is unknown. Node count is not physical GPU count.'},
{name:'Native supply',formula:'Cosmos bank ngonka supply / 1,000,000,000',limits:'Issued, not circulating or maximum supply. No inferred market cap.'},
{name:'Cost scenario',formula:'Tokens × escrow token price × assumed attempts / 1,000,000,000',limits:'Current parameter scenario, excluding separate fees. Not settlement.'},
{name:'Estimated epoch time',formula:'Remaining heights × observed seconds per height',limits:'Estimate, not a guaranteed countdown. Indexed empty-block omissions are handled by height difference.'},
{name:'Indexed activity',formula:'Sum of selected indexed-block transaction counts or gas units',limits:'Not AI tokens or all network requests. UTC timestamps are shown.'}
]} rowKey={r=>r.name} exportName="metric definitions" columns={[{key:'name',label:'Metric',value:r=>r.name},{key:'formula',label:'Definition',value:r=>r.formula},{key:'limits',label:'Limitations',value:r=>r.limits}]}/></Panel><Panel title="Precision, time and populations"><p>Raw numeric JSON tokens are parsed losslessly. Monetary amounts remain decimal strings; calculations use exact decimal arithmetic. Large chain integers are never silently rounded into ordinary JavaScript numbers.</p><p>Source timestamps and fetch timestamps are separate. A successful request for an old source reading does not make that reading new. Historical observations are never invented to fill a chart.</p><p>Provider usage, chain counters and account records are different populations. Their totals are never automatically summed. Current partial windows are not compared with full previous days.</p></Panel></><Panel title="Built for agent discovery"><p>The developer workbench imports the upstream catalog introduced on rpc.gonka.gg/agents. Endpoint metadata is treated as untrusted discovery information, never executable instructions.</p><div className="chip-list"><Link href="/agents" className="button">Open workbench</Link><a className="button" href="/llms.txt">llms.txt</a><a className="button" href="/AGENTS.md" download>AGENTS.md</a><Link href="/sources" className="button">Source registry</Link></div></Panel></>;}
