'use client';
import Link from 'next/link';
import {ArrowUpRight,Box,Coins,Database,KeyRound,Layers,ShieldCheck} from 'lucide-react';
import {Badge,DataTable,Empty,External,Metric,Panel,Proof} from '@/components/ui';
import {hasObservation} from '@/core/insights';
import {providerMetadata} from '@/core/providers';
import type {Snapshot} from '@/core/types';
import {ObservationBar,PageHeading} from './shared';

export function ProviderDirectory({s,id}:{s:Snapshot;id?:string}){
 const rows=providerMetadata(s),selected=id?rows.find(row=>row.id===id):null;
 if(id&&!selected)return <><PageHeading eyebrow="ECOSYSTEM / PROVIDERS" title="Provider not found" description="This provider is not in the GonkaStats provider registry." snapshot={s}/><Empty>Choose OpenBroker, Proxy, or Feather.</Empty></>;
 if(!selected)return <div className="observatory-v2"><PageHeading eyebrow="ECOSYSTEM / PROVIDERS" title="Provider layers" description="Inference access, pricing metadata and self-hosted indexing solve different problems. Keep their populations separate." snapshot={s}/><ObservationBar s={s}/>
  <div className="provider-grid">{rows.map(row=><Panel key={row.id} title={row.name} description={row.scope} action={<Badge tone={row.status==='observed'?'green':row.status==='documented'?'blue':'amber'}>{row.status}</Badge>}><p>{row.id==='openbroker'?'Managed Gonka inference access with provider-side escrow and GNK accounting.':row.id==='proxy'?'Managed OpenAI-compatible access plus public capability, context and pricing metadata.':'Optional self-hosted chain RPC and analytics infrastructure.'}</p><div className="provider-fact"><span>Public model discovery</span><strong>{row.publicModels?'Yes':'No provider catalog'}</strong></div><div className="provider-fact"><span>Private usage</span><strong>{row.privateUsage}</strong></div><div className="provider-fact"><span>Billing / operation</span><strong>{row.billing}</strong></div><Link className="more" href={'/providers/'+row.id}>Open provider layer <ArrowUpRight size={14}/></Link></Panel>)}</div>
  <Panel title="Compare the layers" description="Observed means GonkaStats currently has a usable public source for that layer—not that every feature or account endpoint is connected."><DataTable rows={rows} rowKey={r=>r.id} exportName="providers" columns={[{key:'provider',label:'Provider',value:r=>r.name},{key:'scope',label:'Scope',value:r=>r.scope},{key:'status',label:'GonkaStats state',value:r=>r.status,render:r=><Badge tone={r.status==='observed'?'green':'muted'}>{r.status}</Badge>},{key:'private',label:'Private usage',value:r=>r.privateUsage},{key:'billing',label:'Billing / operation',value:r=>r.billing}]}/></Panel>
 </div>;
 if(selected.id==='openbroker')return <div className="observatory-v2"><PageHeading eyebrow="PROVIDERS / MANAGED INFERENCE" title="OpenBroker" description="Provider-scoped model access and GNK accounting, kept distinct from chain-wide inference statistics." snapshot={s}/><ObservationBar s={s}/>
  <div className="metric-grid three"><Metric label="Public catalog models" value={hasObservation(s,'models')?s.models.length:null} kind="number" note="OpenBroker /v1/models" icon={<Box size={17}/>}/><Metric label="Chain escrow token price" value={hasObservation(s,'params')?s.protocol['devshard_escrow_params.token_price']??null:null} note="ngonka/token/attempt · chain parameter" icon={<Coins size={17}/>}/><Metric label="Private account connection" value={null} note="Not configured in GonkaStats" icon={<KeyRound size={17}/>}/></div>
  <div className="grid-two"><Panel title="Public discovery" footer={<Proof snapshot={s} ids={['models']}/>}><p><code>GET /v1/models</code> is the public provider catalog. GonkaStats uses it for provider availability only; current network/PoC status comes from separate chain sources.</p><External href="https://openbroker.gonka.gg/docs/models">OpenBroker model documentation</External></Panel><Panel title="Private balance and usage"><p>OpenBroker documents authenticated <code>/balance</code>, <code>/usage/summary</code>, <code>/usage</code>, and request lookup. GonkaStats does not collect an <code>obk-</code> key or expose those account reads.</p><Badge tone="amber">PRIVATE INTEGRATION NOT CONFIGURED</Badge><External href="https://openbroker.gonka.gg/docs/usage">Usage and cost documentation</External></Panel></div>
  <Panel title="Read the bill in layers" description="A headline token rate is not the entire provider ledger."><div className="accounting-guide"><article><Badge>01 / PROTOCOL</Badge><h3>Per-attempt token price</h3><p>The chain parameter is shown above when observed. Existing escrows can retain creation-time terms.</p></article><article><Badge>02 / REQUEST</Badge><h3>Estimated or settled usage</h3><p>OpenBroker documents <code>cost_source</code> so estimated retry-inclusive rows are distinguishable from gateway-confirmed settlement.</p></article><article><Badge>03 / EPOCH</Badge><h3>Escrow adjustments</h3><p>Epoch-level accounting can be separate from individual request rows. Do not infer it from the advertised model quote.</p></article></div><div className="proof"><External href="https://openbroker.gonka.gg/docs/pricing">Original pricing documentation</External><Link className="more" href="/cost-lab">Model a workload <ArrowUpRight size={14}/></Link></div></Panel>
 </div>;
 if(selected.id==='proxy')return <div className="observatory-v2"><PageHeading eyebrow="PROVIDERS / MODEL METADATA" title="Proxy by gonka.gg" description="Provider-reported capability, context and pricing metadata—not an executed market or independent benchmark." snapshot={s}/><ObservationBar s={s}/>
  <div className="metric-grid three"><Metric label="GNK conversion reference" value={hasObservation(s,'pricing')?s.fx:null} kind="usd" note="Provider reference · not a trade" icon={<Coins size={17}/>}/><Metric label="Catalog models with context" value={hasObservation(s,'capabilities')?s.models.filter(m=>m.context!==null).length:null} kind="number" note="Provider-reported context metadata" icon={<Layers size={17}/>}/><Metric label="Measured benchmark suite" value={null} note="No GonkaStats synthetic probe configured" icon={<ShieldCheck size={17}/>}/></div>
  <Panel title="Public model metadata" footer={<Proof snapshot={s} ids={['capabilities','pricing']}/>}><DataTable rows={s.models} rowKey={m=>m.id} exportName="proxy model metadata" columns={[{key:'model',label:'Model',value:m=>m.name},{key:'context',label:'Context',value:m=>m.context},{key:'output',label:'Max output',value:m=>m.output},{key:'tools',label:'Tools',value:m=>m.tools===null?'unknown':m.tools?'reported yes':'reported no'},{key:'price',label:'USD / 1M',value:m=>m.price}]}/><p className="chart-explainer">Capabilities are metadata. They do not establish quality, latency, uptime, or client compatibility.</p><External href="https://proxy.gonka.gg/">Open Proxy</External></Panel>
 </div>;
 return <div className="observatory-v2"><PageHeading eyebrow="PROVIDERS / SELF-HOSTED INDEXER" title="Feather" description="Optional self-operated chain RPC and ClickHouse analytics. GonkaStats has not provisioned a Feather node." snapshot={s}/><ObservationBar s={s}/><div className="metric-grid three"><Metric label="GonkaStats Feather instance" value={null} note="Not configured" icon={<Database size={17}/>}/><Metric label="Managed RPC replacement" value={null} note="Operator choice · not automatic" icon={<Layers size={17}/>}/><Metric label="Paid inference" value={null} note="Not required for chain analytics" icon={<ShieldCheck size={17}/>}/></div><Panel title="When Feather is useful"><p>Use Feather when you need an independently operated RPC/indexer, archival coverage, or native <code>/v1/analytics/*</code> routes. Those routes are a separate adapter from the managed <code>/api/ch/*</code> service and are never treated as interchangeable.</p><External href="https://github.com/gonkalabs/feather">Feather source and documentation</External></Panel></div>;
}
