'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Activity,RefreshCw,Download,Star,Clock,ArrowUpRight,Check} from 'lucide-react';
import {Badge,CopyButton,DataTable,Empty,download} from '@/components/ui';
import {elapsedPerBlock,format,shorten,sum} from '@/core/metrics';
import type {Snapshot,Participant} from '@/core/types';
export function PageHeading({eyebrow,title,description,snapshot}:{eyebrow:string;title:string;description:string;snapshot:Snapshot}){const router=useRouter(),[busy,setBusy]=useState(false);return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}<span className="heading-dot">.</span></h1><p>{description}</p></div><div className="heading-actions"><button className="button" onClick={()=>download('gonkastats-observation.json',JSON.stringify(snapshot,null,2))}><Download size={14}/> Export</button><button className="button primary" disabled={busy} onClick={()=>{setBusy(true);router.refresh();setTimeout(()=>setBusy(false),1500);}}><RefreshCw size={14} className={busy?'spin':''}/>{busy?'Checking…':'Refresh'}</button></div></div>;}
export function ObservationBar({s}:{s:Snapshot}){const available=s.sources.filter(x=>x.status!=='unavailable').length,stale=s.sources.filter(x=>x.status==='stale').length;return <div className="observation-bar"><div><span className={'source-dot '+(s.mode==='snapshot'?'snapshot':available===0?'unavailable':stale||available<s.sources.length?'stale':'recent')}/><strong>{s.mode==='snapshot'?'Retained snapshot':'Read-only observation'}</strong><span className="divider"/><span>gonka-mainnet</span><span className="divider"/><span>Block <b>{format(s.epoch?.height,'number')}</b></span></div><div><Clock size={12}/><span>{s.generatedAt.slice(11,19)} UTC</span><span className="divider"/><Link href="/sources">{available}/{s.sources.length} sources{stale?' · '+stale+' stale':''}</Link></div></div>;}
export function EpochTimeline({s}:{s:Snapshot}){const e=s.epoch;if(!e)return <Empty>Epoch data is unavailable.</Empty>;const seconds=elapsedPerBlock(s.blocks),hours=seconds===null?null:e.remaining*seconds/3600;return <><div className="epoch-summary"><div><span className="muted small">CURRENT EPOCH</span><strong>#{e.id}</strong></div><Badge tone="green"><Activity size={12}/>{e.phase}</Badge><div className="epoch-next"><span className="muted small">NEXT EPOCH</span><strong>{hours===null?'—':Math.floor(hours)+'h '+Math.floor((hours%1)*60)+'m'}</strong><small>estimated from observed block rate</small></div></div><div className="epoch-progress" role="progressbar" aria-label="Epoch block progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(e.progress)}><span style={{width:e.progress+'%'}}/></div><div className="progress-label"><span>{e.progress.toFixed(1)}% of block interval</span><span>{format(e.remaining,'number')} blocks remaining</span></div><div className="epoch-stages">{e.boundaries.slice(0,-1).map(b=><div key={b.label} className={e.height>=b.height?'reached':''}><span>{e.height>=b.height?<Check size={11}/>:null}</span><strong>{b.label}</strong><small>{format(b.height,'number')}</small></div>)}</div></>;}
export function Watch({address}:{address:string}){const [on,setOn]=useState(false);useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('gonkastats-watchlist')??'[]');setOn(Array.isArray(saved)&&saved.includes(address));}catch{}},[address]);return <button className={'icon-button watch '+(on?'watched':'')} aria-label={on?'Remove from watchlist':'Add to watchlist'} aria-pressed={on} onClick={()=>{let items:string[]=[];try{const saved=JSON.parse(localStorage.getItem('gonkastats-watchlist')??'[]');if(Array.isArray(saved))items=saved.filter(x=>typeof x==='string');}catch{}const next=on?items.filter(x=>x!==address):[...new Set([...items,address])];localStorage.setItem('gonkastats-watchlist',JSON.stringify(next));setOn(!on);}}><Star size={15} fill={on?'currentColor':'none'}/></button>;}
export function ParticipantsTable({s,compact=false}:{s:Snapshot;compact?:boolean}){const total=Number(sum(s.participants.map(p=>p.weight)));return <DataTable<Participant> rows={compact?s.participants.slice(0,5):s.participants} rowKey={p=>p.address} searchable={!compact} pageSize={compact?5:10} exportName="participants" source={s.sources.find(x=>x.id==='participants')} columns={[{key:'address',label:'Participant',value:p=>p.address,render:p=><div className="address-cell"><span className="avatar">{p.address.slice(-2).toUpperCase()}</span><Link className="mono" href={'/participants/'+p.address}>{shorten(p.address)}</Link></div>},{key:'weight',label:'Epoch weight',value:p=>Number(p.weight),render:p=><span className="mono">{format(p.weight,'number')}</span>},{key:'share',label:'Share',value:p=>total?Number(p.weight)/total:null,render:p=><div className="share-cell"><span>{total?(Number(p.weight)/total*100).toFixed(2)+'%':'—'}</span><i><b style={{width:total?Number(p.weight)/total*100+'%':'0%'}}/></i></div>},{key:'models',label:'Models',value:p=>p.models.length,render:p=><span>{p.models.length} <span className="muted">models</span></span>},{key:'status',label:'Status',value:p=>p.excluded?'Excluded':'Member',render:p=><Badge tone={p.excluded?'amber':'green'}>{p.excluded?'Excluded':'Member'}</Badge>},...(!compact?[{key:'watch',label:'Watch',value:(p:Participant)=>p.address,render:(p:Participant)=><Watch address={p.address}/>}]:[])]}/>;}
export function ModelsList({s,full=false}:{s:Snapshot;full?:boolean}){if(!s.models.length)return <Empty>Model catalog is unavailable.</Empty>;return <div className={full?'model-grid':'model-list'}>{s.models.map((m,i)=><Link key={m.id} href={'/models/'+m.slug} className="model-item"><span className={'model-icon model-'+i}>{m.name.slice(0,1)}</span><div><strong>{m.name}</strong><small>{format(m.context)} context · {m.tools===true?'Tool calling':m.tools===false?'No tool support':'Tools unknown'}</small>{full&&<p className="small muted">{m.id}<br/>{m.reasoning===true?'Reasoning supported':m.reasoning===false?'No reasoning support':'Reasoning unknown'} · {format(m.vram)} GB reported VRAM</p>}</div><div className="model-price"><strong>{format(m.price,'usd')}</strong><small>/ 1M tokens</small></div><ArrowUpRight size={14}/></Link>)}</div>;}
export function ProposalList({s,compact=false}:{s:Snapshot;compact?:boolean}){return <div className="proposal-list">{s.proposals.slice(0,compact?3:20).map(p=><Link href={'/governance/'+p.id} key={p.id}><span className="proposal-number">#{p.id}</span><div><strong>{p.title}</strong><small>{p.messages.map(m=>m.split('.').at(-1)).join(' · ')}</small></div><Badge tone={p.status==='PASSED'?'green':p.status==='VOTING_PERIOD'?'blue':'muted'}>{p.status.replaceAll('_',' ').toLowerCase()}</Badge><ArrowUpRight size={13}/></Link>)}{!s.proposals.length&&<Empty>No governance records are currently available.</Empty>}</div>;}
export function BlocksTable({s,compact=false}:{s:Snapshot;compact?:boolean}){return <DataTable rows={compact?s.blocks.slice(0,6):s.blocks} rowKey={b=>String(b.height)} searchable={!compact} exportName="blocks" source={s.sources.find(x=>x.id==='blocks')} columns={[{key:'height',label:'Block',value:b=>b.height,render:b=><Link className="mono accent" href={'/blocks/'+b.height}>#{b.height}</Link>},{key:'time',label:'Time (UTC)',value:b=>b.time,render:b=><span className="mono muted">{b.time.slice(11,19)}</span>},{key:'tx',label:'Transactions',value:b=>b.transactions},{key:'gas',label:'Gas used',value:b=>Number(b.gas),render:b=>format(b.gas)}]}/>;}
export function ProtocolTable({s,group}:{s:Snapshot;group:string}){const rows=Object.entries(s.protocol).filter(([k])=>k.startsWith(group+'.')).map(([key,value])=>({key:key.split('.').slice(1).join('.'),value}));return <DataTable rows={rows} rowKey={r=>r.key} exportName="parameters" source={s.sources.find(x=>x.id==='params')} columns={[{key:'name',label:'Parameter',value:r=>r.key,render:r=><code>{r.key}</code>},{key:'value',label:'Current chain value',value:r=>r.value,render:r=><code>{r.value}</code>}]}/>;}
export function RawRecord({data}:{data:unknown}){const text=JSON.stringify(data,null,2);return <div className="raw-record"><div className="raw-toolbar"><span>Source JSON · read-only</span><CopyButton text={text} label="Copy JSON"/></div><pre>{text}</pre></div>;}
