'use client';
import {useState} from 'react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,PieChart,Pie,Cell} from 'recharts';
import {format,shorten,sum,number} from '@/core/metrics';
import type {Block,Participant,HistoryPoint} from '@/core/types';
import {Empty} from './ui';
const colors=['#49d9bc','#78a8f6','#ae94e8','#d9b36a','#e88b9e','#3a5264'];
export function ActivityChart({blocks}:{blocks:Block[]}){
 const [count,setCount]=useState(30),[metric,setMetric]=useState<'transactions'|'gas'>('transactions'),[table,setTable]=useState(false);
 const rows=blocks.slice(0,count).reverse().map(b=>({...b,gas:number(b.gas),timeLabel:b.time.slice(11,16)}));
 if(!blocks.length)return <Empty>Indexed blocks are unavailable. No chart values have been fabricated.</Empty>;
 return <><div className="chart-controls"><div className="segmented" aria-label="Activity measure">{(['transactions','gas'] as const).map(v=><button key={v} aria-pressed={metric===v} onClick={()=>setMetric(v)}>{v==='gas'?'Gas used':'Transactions'}</button>)}</div><div className="segmented" aria-label="Number of indexed records">{[15,30,60].map(n=><button key={n} disabled={blocks.length<n} aria-pressed={count===n} onClick={()=>setCount(n)}>{n} blocks</button>)}</div></div><div className="chart-summary"><strong>{format(metric==='transactions'?rows.reduce((a,b)=>a+b.transactions,0):sum(rows.map(b=>String(b.gas??0))))}</strong><span>{metric==='transactions'?'transactions in selected indexed records':'gas units in selected indexed records'}</span></div><div className="chart-box" data-testid="activity-chart" data-points={rows.length}><ResponsiveContainer width="100%" height={220} minWidth={0}><AreaChart data={rows} accessibilityLayer margin={{top:10,right:10,left:-15,bottom:0}}><defs><linearGradient id="activity-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#49d9bc" stopOpacity={0.23}/><stop offset="100%" stopColor="#49d9bc" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="timeLabel" tickLine={false} axisLine={false} minTickGap={40} tick={{fill:'var(--muted)',fontSize:11}}/><YAxis tickLine={false} axisLine={false} tick={{fill:'var(--muted)',fontSize:11}} tickFormatter={n=>format(n)}/><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)',borderRadius:8,color:'var(--text)'}} labelFormatter={(_,p)=>p[0]?.payload?.height?'Block '+p[0].payload.height:''}/><Area dataKey={metric} name={metric==='gas'?'Gas used':'Transactions'} type="linear" stroke="#49d9bc" fill="url(#activity-fill)" strokeWidth={2} isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer></div><div className="chart-caption"><span>UTC · indexed records, not all blocks</span><button className="text-button" onClick={()=>setTable(!table)} aria-expanded={table}>{table?'Hide':'View'} data table</button></div>{table&&<div className="table-scroll"><table><caption className="sr-only">Indexed activity data</caption><thead><tr><th>Height</th><th>UTC time</th><th>Transactions</th><th>Gas used</th></tr></thead><tbody>{rows.map(r=><tr key={r.height}><td>{r.height}</td><td>{r.time}</td><td>{r.transactions}</td><td>{r.gas??'Unknown'}</td></tr>)}</tbody></table></div>}</>;
}
export function WeightChart({participants}:{participants:Participant[]}){
 const total=Number(sum(participants.map(p=>p.weight)));if(!participants.length||!total)return <Empty>Epoch weight data is not available.</Empty>;
 const top=participants.slice(0,5).map(p=>({name:shorten(p.address,4),value:Number(p.weight)})),other=Math.max(0,total-top.reduce((a,b)=>a+b.value,0)),data=[...top,...(other?[{name:'Other members',value:other}]:[])];
 return <div className="weight-chart"><div className="donut"><ResponsiveContainer width="100%" height={184} minWidth={0}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={62} outerRadius={83} paddingAngle={2} stroke="none" isAnimationActive={false}>{data.map((p,i)=><Cell key={p.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:'var(--panel)',border:'1px solid var(--border)',borderRadius:8,color:'var(--text)'}}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{participants.length}</strong><span>epoch members</span></div></div><div className="donut-legend">{data.map((r,i)=><div key={r.name}><span><i style={{background:colors[i%colors.length]}}/>{r.name}</span><strong>{(r.value/total*100).toFixed(1)}%</strong></div>)}</div><p className="small muted">Declared epoch weights, including members later marked excluded. Not consensus voting power.</p></div>;
}
export function HistoryChart({points,field='weight'}:{points:HistoryPoint[];field?:'weight'|'price'}){if(points.filter(p=>p[field]!==null).length<2)return <Empty title="History starts with observation">Connect PostgreSQL and run the collector to accumulate genuine history. At least two observations are required; no backfilled demo series is shown.</Empty>;return <ResponsiveContainer width="100%" height={250}><AreaChart data={points.map(p=>({...p,[field]:number(p[field]),time:p.at.slice(5,16).replace('T',' ')}))}><XAxis dataKey="time" minTickGap={70} tick={{fill:'var(--muted)',fontSize:11}}/><YAxis tickFormatter={n=>format(n)} tick={{fill:'var(--muted)',fontSize:11}}/><CartesianGrid vertical={false} stroke="var(--border)"/><Tooltip/><Area dataKey={field} type="linear" stroke="#49d9bc" fill="#49d9bc22" isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer>;}
