'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useEffect,useState,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Activity,LayoutDashboard,Network,Layers,Users,Box,Coins,Wallet,Landmark,Code2,BookOpen,Radio,ArrowLeftRight,Terminal,Search,Sun,Moon,Menu,X,ChevronRight,ExternalLink,ShieldCheck,BarChart3,Calculator,Braces,Cpu,Star,GitBranch} from 'lucide-react';
import {bech32Address,slugFor} from '@/core/metrics';
import type {Model} from '@/core/types';
const groups=[{title:'OBSERVATORY',items:[['/','Overview',LayoutDashboard],['/activity','Activity Lab',Activity],['/learn','Gonka field guide',BookOpen],['/network','Network',Network],['/protocol','Protocol',GitBranch],['/hardware','Hardware',Cpu],['/epochs','Epochs',Layers],['/participants','Participants',Users],['/inference','Inference',Activity]]},{title:'ECOSYSTEM',items:[['/models','Models',Box],['/providers','Providers',ArrowLeftRight],['/markets','Markets',BarChart3],['/tokenomics','Tokenomics',Coins],['/treasury','Treasury',Wallet],['/governance','Governance',Landmark],['/pulse','Pulse & media',Radio],['/ecosystem','Community directory',Network]]},{title:'WORKSPACE',items:[['/watchlist','Watchlist',Star],['/workload','Context planner',Box],['/cost-lab','Cost lab',Calculator],['/epoch-diff','Epoch diff',ArrowLeftRight],['/blocks','Explorer',Braces],['/signals','Signal desk',ShieldCheck],['/agents','Agent workbench',Terminal],['/developers','Developers',Code2],['/sources','Sources & status',BookOpen]]}] as const;
const utilityRouteNames={'/methodology':'Methodology','/changelog':'Changelog','/about':'About','/privacy':'Privacy'} as const;
export const routeNames:Record<string,string>={...Object.fromEntries(groups.flatMap(g=>g.items.map(i=>[i[0],i[1]]))),...utilityRouteNames};
function Mark(){return <svg viewBox="0 0 36 36" fill="none" aria-hidden="true"><path d="M26 7H13L5 15v13h14l12-12H18l-5 5h9l-5 5H9V17l6-6h7z" fill="currentColor"/></svg>;}
export function Shell({children,models}:{children:ReactNode;models:Model[]}){
 const path=usePathname(),router=useRouter();const [nav,setNav]=useState(false),[search,setSearch]=useState(false),[q,setQ]=useState(''),[theme,setTheme]=useState('dark'),[catalog,setCatalog]=useState(models);
 useEffect(()=>{if(search&&!catalog.length){const controller=new AbortController();fetch('/api/v1/models',{signal:controller.signal}).then(r=>r.json()).then(j=>{if(Array.isArray(j.data))setCatalog(j.data);}).catch(()=>{});return()=>controller.abort();}},[search,catalog.length]);
 useEffect(()=>{setTheme(document.documentElement.dataset.theme??'dark');const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(x=>!x);}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[]);
 useEffect(()=>{setNav(false);setSearch(false);},[path]);
 const navigation=<><Link href="/" className="brand"><Mark/><span>gonka<span className="brand-light">stats</span><small>BY NOSYT LABS</small></span></Link><nav aria-label="Main navigation">{groups.map(g=><div className="nav-group" key={g.title}><div className="nav-label">{g.title}</div>{g.items.map(([href,label,Icon])=>{const active=path===href||(href!=='/'&&path.startsWith(href+'/'));return <Link key={href} href={href} onClick={()=>setNav(false)} aria-current={active?'page':undefined} className={'nav-link '+(active?'active':'')}><Icon size={16}/><span>{label}</span></Link>;})}</div>)}</nav><div className="sidebar-bottom"><span className="connection-dot"/><div>Independent observatory<small>Read-only. No wallet required.</small></div></div></>;
 const query=q.trim().toLowerCase();const results=[...Object.entries(routeNames).filter(([,name])=>name.toLowerCase().includes(query)).map(([href,name])=>({href,name})),...catalog.filter(m=>m.name.toLowerCase().includes(query)).map(m=>({href:'/models/'+slugFor(m.id),name:m.name}))].slice(0,10);
 const lookupValue=q.trim();const lookup=/^\d{1,10}$/.test(lookupValue)?'/blocks/'+lookupValue:/^(0x)?[a-fA-F0-9]{64}$/.test(lookupValue)?'/transactions/'+lookupValue.replace(/^0x/,''):bech32Address(lookupValue)?'/addresses/'+lookupValue:null;
 return <><a className="skip-link" href="#main-content">Skip to content</a><aside className="sidebar">{navigation}</aside><div className="workspace"><header className="topbar"><div className="breadcrumb"><Dialog.Root open={nav} onOpenChange={setNav}><Dialog.Trigger asChild><button className="icon-button mobile-menu" aria-label="Open navigation"><Menu size={20}/></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="mobile-nav"><Dialog.Title className="sr-only">Navigation</Dialog.Title><Dialog.Description className="sr-only">Browse the observatory</Dialog.Description><Dialog.Close className="mobile-close icon-button" aria-label="Close navigation"><X size={18}/></Dialog.Close>{navigation}</Dialog.Content></Dialog.Portal></Dialog.Root><span className="breadcrumb-root">Observatory</span><ChevronRight size={13}/><span>{routeNames['/'+path.split('/')[1]]??'Details'}</span></div><div className="topbar-actions"><button className="search-trigger" aria-label="Search anything" onClick={()=>setSearch(true)}><Search size={15}/><span>Search anything</span><kbd>⌘ K</kbd></button><button className="icon-button" aria-label="Toggle color theme" onClick={()=>{const t=theme==='dark'?'light':'dark';setTheme(t);document.documentElement.dataset.theme=t;try{localStorage.setItem('gonkastats-theme',t);}catch{}}}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><a className="top-source" href="https://gonka.ai/docs/" target="_blank" rel="noopener noreferrer">Gonka docs<ExternalLink size={12}/></a></div></header><main id="main-content" tabIndex={-1}>{children}</main><footer className="site-footer"><span>GonkaStats <span className="muted">/ Independent analytics by Nosyt Labs</span></span><div><Link href="/methodology">Methodology</Link><Link href="/sources">Data sources</Link><Link href="/about">About</Link><Link href="/privacy">Privacy</Link><a href="https://github.com/NosytLabs/Gonkastats" target="_blank" rel="noopener noreferrer">GitHub</a><a href="https://x.com/gonka_ai" target="_blank" rel="noopener noreferrer">X · @gonka_ai</a><a href="https://discord.gg/REcpeYc7P7" target="_blank" rel="noopener noreferrer">Discord</a><a href="https://t.me/gonka_gg" target="_blank" rel="noopener noreferrer">Telegram</a></div></footer></div>
 <Dialog.Root open={search} onOpenChange={setSearch}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="search-dialog"><Dialog.Title>Explore Gonka</Dialog.Title><Dialog.Description>Search pages, models, block heights, transaction hashes, or checksummed Gonka addresses.</Dialog.Description><Dialog.Close className="dialog-close icon-button" aria-label="Close search"><X size={18}/></Dialog.Close><label className="command-input"><Search size={20}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} aria-label="Search pages and chain data" placeholder="An address, block, model, or page…" onKeyDown={e=>{if(e.key==='Enter'&&(lookup||results[0])){setSearch(false);router.push(lookup??results[0].href);}}}/></label><div className="command-results">{lookup&&<Link href={lookup} onClick={()=>setSearch(false)}>Look up {q}<ChevronRight size={16}/></Link>}{results.map(r=><Link key={r.href} href={r.href} onClick={()=>setSearch(false)}>{r.name}<ChevronRight size={15}/></Link>)}{!results.length&&!lookup&&<p>No result. Chain addresses must have a valid checksum.</p>}</div></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
