'use client';
import Link from 'next/link';
import {useState,type ReactNode} from 'react';
import {ArrowUpRight,Copy,Check,Info,Download,ChevronLeft,ChevronRight,Search,ArrowDownUp,AlertCircle} from 'lucide-react';
import {csv,format} from '@/core/metrics';
import {compareCells} from '@/core/insights';
import type {Source,Snapshot} from '@/core/types';
export function Icon({children}:{children:ReactNode}){return <span className="icon-box">{children}</span>;}
export function Badge({children,tone='muted'}:{children:ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>;}
export function External({href,children}:{href:string;children:ReactNode}){return <a className="external" href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={13}/></a>;}
export function CopyButton({text,label='Copy'}:{text:string;label?:string}){const [state,setState]=useState('');return <button className="button ghost compact" aria-label={label} onClick={async()=>{try{await navigator.clipboard.writeText(text);setState('Copied');}catch{setState('Copy unavailable');}setTimeout(()=>setState(''),2000);}}>{state==='Copied'?<Check size={14}/>:<Copy size={14}/>}<span aria-live="polite">{state||label}</span></button>;}
export function SourceNote({source}:{source?:Source}){if(!source)return <span className="muted small">Source not connected</span>;return <details className="source-note"><summary><Info size={12}/>{source.name}<span className={'source-dot '+source.status}/>{source.status==='recent'?'Recently fetched':source.status}</summary><div><strong>{source.scope} · {source.name}</strong><p>{source.coverage}</p><p>Fetched: {source.fetchedAt.replace('T',' ').slice(0,19)} UTC<br/>Source time: {source.sourceTime?.replace('T',' ').slice(0,19)??'Not supplied'}</p>{source.error&&<p className="warning-text">{source.error}</p>}<External href={source.url}>Inspect upstream source</External></div></details>;}
export function Proof({snapshot,ids}:{snapshot:Snapshot;ids:string[]}){return <div className="proof">{ids.map(id=><SourceNote key={id} source={snapshot.sources.find(s=>s.id===id)}/>)}</div>;}
export function Panel({title,description,action,children,className='',footer}:{title:string;description?:string;action?:ReactNode;children:ReactNode;className?:string;footer?:ReactNode}){return <section className={'panel '+className}><header className="panel-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</header><div className="panel-body">{children}</div>{footer&&<footer className="panel-foot">{footer}</footer>}</section>;}
export function More({href,children='View all'}:{href:string;children?:ReactNode}){return <Link className="more" href={href}>{children}<ArrowUpRight size={14}/></Link>;}
export function Metric({label,value,kind='compact',note,icon,accent=false}:{label:string;value:unknown;kind?:'compact'|'number'|'usd'|'percent';note:string;icon:ReactNode;accent?:boolean}){return <div className={'metric '+(accent?'metric-accent':'')}><div className="metric-label">{label}{icon}</div><div className="metric-value" title={value==null?'Unavailable':String(value)}>{format(value,kind)}</div><div className="metric-note">{note}</div></div>;}
export function Empty({title='Data not available',children,href}:{title?:string;children:ReactNode;href?:string}){return <div className="empty"><AlertCircle size={22}/><h3>{title}</h3><p>{children}</p>{href&&<External href={href}>View original source</External>}</div>;}
export function download(name:string,content:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
export type Column<T>={key:string;label:string;render?:(row:T)=>ReactNode;value:(row:T)=>string|number|null;};
export function DataTable<T>({rows,columns,rowKey,searchable=true,pageSize=10,exportName='data',source}:{rows:T[];columns:Column<T>[];rowKey:(row:T)=>string;searchable?:boolean;pageSize?:number;exportName?:string;source?:Source}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState<string|null>(null),[desc,setDesc]=useState(false),[page,setPage]=useState(0);
 const filtered=rows.filter(r=>columns.some(c=>String(c.value(r)??'').toLowerCase().includes(query.toLowerCase())));const c=columns.find(x=>x.key===sort);if(c)filtered.sort((a,b)=>compareCells(c.value(a),c.value(b),desc));
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),current=Math.min(page,pages-1),view=filtered.slice(current*pageSize,(current+1)*pageSize);
 return <div className="data-table">{searchable&&<div className="table-controls"><label className="search-field"><Search size={15}/><input aria-label={'Search '+exportName} placeholder={'Search '+exportName+'…'} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>{(query||sort||page>0)&&<button className="button ghost compact reset-filter" onClick={()=>{setQuery('');setSort(null);setDesc(false);setPage(0);}}>Reset table</button>}<button className="button ghost compact" onClick={()=>download(exportName+'.csv',csv(filtered.map(r=>Object.fromEntries([...columns.map(c=>[c.label,c.value(r)]),['Source',source?.url??'Locally derived / see methodology'],['Fetched at',source?.fetchedAt??''],['Source time',source?.sourceTime??''],['Status',source?.status??''],['Coverage',source?.coverage??'Filtered rows only']]))),'text/csv')}><Download size={14}/> Export CSV</button></div>}
 <div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c.key} scope="col" aria-sort={sort===c.key?(desc?'descending':'ascending'):'none'}><button onClick={()=>{setPage(0);setSort(c.key);setDesc(sort===c.key?!desc:false);}}>{c.label}<ArrowDownUp size={11}/></button></th>)}</tr></thead><tbody>{view.map(row=><tr key={rowKey(row)}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):c.value(row)??'—'}</td>)}</tr>)}{!view.length&&<tr><td colSpan={columns.length} className="no-results">No records match this view.</td></tr>}</tbody></table></div>
 {searchable&&<div className="pagination"><span>{filtered.length?current*pageSize+1:0}–{Math.min((current+1)*pageSize,filtered.length)} of {filtered.length} records</span><div><button aria-label="Previous page" className="button ghost compact" disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={15}/></button><span>{current+1} / {pages}</span><button aria-label="Next page" className="button ghost compact" disabled={current>=pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={15}/></button></div></div>}
 </div>;
}
