import {lookupPath} from '@/core/lookup';
import {notFound,redirect} from 'next/navigation';
import {getSnapshot,detail} from '@/core/service';
import {history} from '@/db/store';
import {bech32Address} from '@/core/metrics';
import {Overview} from '@/features/overview';
import {NetworkView,ParticipantsView,EpochsView,InferenceView} from '@/features/network';
import {ModelsView,Markets,Economics,Governance,AccountView} from '@/features/ecosystem';
import {Agents,CostLab,EpochDiffView} from '@/features/tools';
import {Sources,Signals,Pulse,Documentation} from '@/features/platform';
import {ProtocolRadar} from '@/features/protocol';
import {ProviderDirectory} from '@/features/providers';
import {Explorer} from '@/features/explorer';
import {pageMetadata} from '@/core/seo';
export const dynamic='force-dynamic';
export const runtime='nodejs';
const allowed=new Set(['','network','protocol','participants','epochs','inference','models','providers','brokers','proxy','markets','tokenomics','rewards','treasury','vesting','devshards','bridge','governance','blocks','transactions','addresses','pulse','media','agents','cost-lab','epoch-diff','signals','sources','status','developers','methodology','changelog','intelligence','account']);
export async function generateMetadata({params}:{params:Promise<{route?:string[]}>}){const r=(await params).route??[];if(r.length>2||!allowed.has(r[0]??'')||r.some(segment=>/[\\/\u0000-\u001f]/.test(segment)))notFound();if(r[0]==='models'&&r[1]){if(!/^(?:[0-9a-f]{2}){1,250}$/.test(r[1]))notFound();const snapshot=await getSnapshot();const observed=snapshot.sources.some(source=>source.id==='models'&&source.status!=='unavailable');return pageMetadata('/'+r.join('/'),{model:observed?snapshot.models.find(model=>model.slug===r[1])??null:null});}return pageMetadata('/'+r.join('/'));}
export default async function Page({params}:{params:Promise<{route?:string[]}>}){const routes=(await params).route??[],section=routes[0]??'',id=routes[1];if(routes.length>2||!allowed.has(section))notFound();if(section==='brokers'){if(id&&!['openbroker','proxy','feather'].includes(id))notFound();redirect('/providers'+(id?'/'+id:''));}if(section==='proxy'){if(id)notFound();redirect('/providers/proxy');}if(section==='media'){if(id)notFound();redirect('/pulse');}if(section==='status'){if(id)notFound();redirect('/sources');}if(id){const detailKinds=['models','participants','epochs','providers','governance','blocks','transactions','addresses'];if(!detailKinds.includes(section))notFound();if(['participants','addresses'].includes(section)&&!bech32Address(id))notFound();if(['epochs','governance','blocks'].includes(section)&&!lookupPath(section,id))notFound();if(section==='transactions'&&!/^[a-fA-F0-9]{64}$/.test(id))notFound();if(section==='models'&&!/^(?:[0-9a-f]{2}){1,250}$/.test(id))notFound();if(section==='providers'&&!['openbroker','proxy','feather'].includes(id))notFound();}
const s=await getSnapshot();if(section==='models'&&id&&s.sources.some(source=>source.id==='models'&&source.status!=='unavailable')&&!s.models.some(model=>model.slug===id))notFound();const getHistory=async()=>{try{return await history();}catch{return [];}};
switch(section){case '':return <Overview s={s}/>;case 'network':return <NetworkView s={s} points={await getHistory()}/>;case 'protocol':return <ProtocolRadar s={s}/>;case 'participants':return <ParticipantsView s={s} address={id}/>;case 'epochs':return <EpochsView s={s} id={id} detail={id&&id!==String(s.epoch?.id)?await detail('epochs',id):null}/>;case 'inference':return <InferenceView s={s}/>;case 'models':return <ModelsView s={s} slug={id}/>;case 'providers':return <ProviderDirectory s={s} id={id}/>;case 'markets':return <Markets s={s} points={await getHistory()}/>;case 'tokenomics':case 'rewards':case 'treasury':case 'vesting':case 'devshards':case 'bridge':return <Economics s={s} section={section}/>;case 'governance':return <Governance s={s} id={id} detail={id?await detail('governance',id):null}/>;case 'blocks':case 'transactions':return <Explorer s={s} kind={section} id={id} detail={id?await detail(section,id):null}/>;case 'addresses':if(!id)notFound();return <AccountView s={s} id={id} detail={await detail('addresses',id)}/>;case 'pulse':return <Pulse s={s}/>;case 'agents':return <Agents s={s}/>;case 'cost-lab':return <CostLab s={s}/>;case 'epoch-diff':return <EpochDiffView s={s}/>;case 'signals':return <Signals s={s}/>;case 'sources':return <Sources s={s}/>;default:return <Documentation s={s} section={section}/>;}}
