import {historyWithGaps} from './audit';
import type {Snapshot,HistoryPoint} from './types';
import {hasObservation,overviewFacts} from './insights';
export function metricData(s:Snapshot){const facts=overviewFacts(s);return [
{id:'gnk_conversion_reference',label:'GNK conversion reference',value:hasObservation(s,'pricing')?s.fx:null,unit:'USD/GNK',sourceId:'pricing',scope:'provider',definition:'Proxy conversion reference, not an executed trade.'},
{id:'issued_supply',label:'Native issued supply',value:hasObservation(s,'supply')?s.totalSupply:null,unit:'GNK',sourceId:'supply',scope:'chain',definition:'Issued native bank supply; not circulating or maximum supply.'},
{id:'epoch_members',label:'Declared epoch members',value:facts.members===null?null:String(facts.members),unit:'members',sourceId:'participants',scope:'chain',definition:'Includes separately marked exclusions.'},
{id:'declared_weight',label:'Declared epoch weight',value:facts.weight,unit:'weight',sourceId:'participants',scope:'chain',definition:'Sum of declared membership weight, not current consensus power.'},
{id:'excluded_members',label:'Marked exclusions',value:facts.excluded===null?null:String(facts.excluded),unit:'members',sourceId:'participants',scope:'chain',definition:'Count of source-reported exclusions among declared members.'},
{id:'available_models',label:'Available models',value:facts.models===null?null:String(facts.models),unit:'models',sourceId:'models',scope:'provider',definition:'Count in the OpenBroker catalog.'},
{id:'matched_gpus',label:'Matched GPU registrations',value:facts.gpus,unit:'registered GPUs',sourceId:'hardware',scope:'chain',definition:'Registrations matched to declared epoch ML-node IDs; not independently verified physical inventory.'},
{id:'escrow_token_price',label:'Escrow token price',value:hasObservation(s,'params')?s.protocol['devshard_escrow_params.token_price']??null:null,unit:'ngonka/token/attempt',sourceId:'params',scope:'chain',definition:'Current parameter; historical escrow terms can differ.'}
];}
export function healthData(s:Snapshot){const usable=s.sources.filter(x=>x.status!=='unavailable').length,recent=s.sources.filter(x=>x.status==='recent').length;return {status:usable===0?'unavailable':s.mode==='snapshot'?'snapshot':recent===s.sources.length?'ok':'degraded',mode:s.mode,usableSources:usable,recentSources:recent,totalSources:s.sources.length,observationTime:s.generatedAt,history:process.env.DATABASE_URL?'configured':'not-configured'};}
export function chartData(points:HistoryPoint[],metric:'weight'|'price'|'participants',maxPoints:number){const rawCount=points.length;points=historyWithGaps(points);const size=Math.max(1,Math.ceil(points.length/maxPoints));const rows:{at:string;value:string|null;observations:number;containsGap:boolean}[]=[];for(let i=0;i<points.length;i+=size){const bucket=points.slice(i,i+size),last=bucket[bucket.length-1],gap=bucket.some(p=>p[metric]===null);rows.push({at:last.at,value:gap?null:String(last[metric]),observations:bucket.filter(p=>!p.gap).length,containsGap:gap});}return {metric,unit:metric==='price'?'USD/GNK':metric==='participants'?'members':'declared weight',points:rows,sampling:size===1?'none':'last observed value per bucket; any missing observation preserves a gap',rawPointCount:rawCount,gapPolicy:'Break lines across missing collection intervals longer than 15 minutes',returnedPointCount:rows.length,firstObservation:points[0]?.at??null,lastObservation:points.at(-1)?.at??null};}
