export interface Parameter {name:string;description:string;default?:string;required?:boolean;enum?:string[];type?:'integer'|'string';min?:number;max?:number;}
export interface ApiDefinition {id:string;group:string;title:string;description:string;parameters:Parameter[];cache:string;}
const paging:Parameter[]=[{name:'q',description:'Case-insensitive text filter; at most 160 characters.'},{name:'limit',description:'Maximum records returned.',type:'integer',min:1,max:100,default:'20'},{name:'offset',description:'Offset within the retained source window, not global history.',type:'integer',min:0,max:100000,default:'0'}];
const range:Parameter[]=[{name:'hours',description:'Retained observation window, in hours.',type:'integer',min:1,max:168,default:'24'}];
export const apiDefinitions:ApiDefinition[]=[
{id:'overview',group:'Core',title:'Full observation',description:'The normalized public snapshot with source-specific freshness, scope and coverage. Missing data remains null.',parameters:[],cache:'Shared observation cache: 120 seconds'},
{id:'metrics',group:'Core',title:'Defined headline metrics',description:'Metric values together with units and source IDs. No inferred circulating market cap, artificial uptime or invented GPU equivalence.',parameters:[],cache:'Shared observation cache'},
{id:'models',group:'Core',title:'Model catalog',description:'OpenBroker model availability, joined to separately attributed Proxy capabilities and advertised prices.',parameters:[...paging,{name:'capability',description:'Require a provider-reported capability.',enum:['tools','reasoning']},{name:'sort',description:'Sort order.',enum:['name','context','price'],default:'name'}],cache:'Shared observation cache'},
{id:'participants',group:'Core',title:'Epoch membership',description:'Declared members and separately marked exclusions. Weight is not assumed to be current consensus voting power.',parameters:paging,cache:'Shared observation cache'},
{id:'blocks',group:'Explorer',title:'Indexed block window',description:'Recently retained indexed block records, which can omit empty blocks. Use lookup for a canonical block.',parameters:paging,cache:'Shared observation cache'},
{id:'epochs',group:'Core',title:'Current epoch',description:'The latest epoch and its returned block boundaries. Historical membership is available through lookup and epoch-diff.',parameters:[],cache:'Shared observation cache'},
{id:'inference',group:'Core',title:'Reported inference statistics',description:'Per-model dAPI statistics in the recorded UTC window. Global DevShard coverage is not established. Unavailable source is explicit.',parameters:[],cache:'Shared observation cache'},
{id:'live',group:'Explorer',title:'Observed activity feed',description:'Recent indexed-block observations, not a complete transaction/inference event stream. This is a polling endpoint, not a WebSocket.',parameters:[{name:'limit',description:'Records, newest first.',type:'integer',min:1,max:100,default:'20'},{name:'since',description:'Optional ISO 8601 UTC lower bound, e.g. 2026-09-21T00:00:00Z.'}],cache:'Shared observation cache'},
{id:'history',group:'History',title:'Retained observations',description:'Actual PostgreSQL observations. No database means an empty dataset with an explicit not-configured state.',parameters:range,cache:'Database query; at most 2,048 points'},
{id:'charts',group:'History',title:'Bounded chart series',description:'A selected metric from retained observations. Samples use actual timestamps; buckets containing missing readings become gaps.',parameters:[...range,{name:'metric',description:'Metric to chart.',enum:['weight','price','participants'],default:'weight'},{name:'maxPoints',description:'Maximum returned samples.',type:'integer',min:2,max:200,default:'200'}],cache:'Database query with bounded sampling'},
{id:'simulate-cost',group:'Labs',title:'Exact workload cost scenario',description:'The same deterministic decimal function used by Cost Lab. Advertised USD, single-attempt GNK, and assumed retry cost stay separate. Not a bill.',parameters:[{name:'prompt',description:'Prompt tokens per request; whole number, 0 to 10^15.',default:'1000000'},{name:'completion',description:'Completion tokens per request; same bounds.',default:'250000'},{name:'requests',description:'Number of requests; same bounds.',default:'1'},{name:'attempts',description:'Assumed average attempts, 1 to 3.',default:'1.5'},{name:'model',description:'Exact discovered model ID; defaults to the first catalog model.'}],cache:'Current source rates + deterministic calculation'},
{id:'epoch-diff',group:'Labs',title:'Compare two epochs',description:'Compare declared membership and exact weight deltas, with both original source URLs. At most 30 epochs apart.',parameters:[{name:'from',description:'Earlier epoch.',type:'integer',min:1,max:1000000,required:true},{name:'to',description:'Later epoch.',type:'integer',min:2,max:1000000,required:true}],cache:'Detail cache: 300 seconds'},
{id:'lookup',group:'Explorer',title:'Validated chain lookup',description:'Curated lookups only. No arbitrary URLs, SQL, transaction broadcasts or billable inference.',parameters:[{name:'kind',description:'Read type.',enum:['addresses','history','transactions','blocks','vesting','epochs','governance'],required:true},{name:'id',description:'Checksummed address, 64-character hex hash, or numeric ID appropriate to the kind.',required:true}],cache:'Detail cache: 300 seconds; 30 new reads/minute/process'},
{id:'sources',group:'Provenance',title:'Source health and provenance',description:'Source URLs, original timestamps, retrieval timestamps, scopes, errors and coverage limitations.',parameters:[],cache:'Shared observation cache'},
{id:'health',group:'Provenance',title:'Data pipeline health',description:'Current source availability and deployment mode, not a historical uptime percentage. HTTP 503 when no source is usable.',parameters:[],cache:'Shared observation cache'},
{id:'status',group:'Provenance',title:'Status alias',description:'Same source-aware health summary as /health.',parameters:[],cache:'Shared observation cache'},
{id:'endpoints',group:'Developers',title:'Upstream discovery catalog',description:'Imported rpc.gonka.gg endpoint definitions. Catalogued write endpoints are documentation only and cannot be executed here.',parameters:[...paging,{name:'method',description:'HTTP method metadata filter.',enum:['GET','POST','ALL'],default:'GET'}],cache:'Shared observation cache'},
{id:'openapi',group:'Developers',title:'OpenAPI specification',description:'Generated from this implementation registry. The catalog describes only routes actually handled by this application.',parameters:[],cache:'Build configuration'}
];
export function validateQuery(def:ApiDefinition,query:URLSearchParams):Record<string,string>{const result:Record<string,string>={};for(const key of query.keys())if(!def.parameters.some(p=>p.name===key))throw new Error('Unknown parameter: '+key);for(const p of def.parameters){if(query.getAll(p.name).length>1)throw new Error('Repeated parameter: '+p.name);const value=query.get(p.name)??p.default;if(value===undefined||value===''){if(p.required)throw new Error('Required parameter: '+p.name);continue;}if(value.length>500)throw new Error('Parameter too long: '+p.name);if(p.name==='q'&&value.length>160)throw new Error('Search is limited to 160 characters');if(p.enum&&!p.enum.includes(value))throw new Error('Invalid '+p.name);if(p.type==='integer'&&(!/^\d+$/.test(value)||!Number.isSafeInteger(Number(value))||Number(value)<(p.min??0)||Number(value)>(p.max??Number.MAX_SAFE_INTEGER)))throw new Error('Invalid '+p.name);result[p.name]=value;}if(result.since&&(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/.test(result.since)||!Number.isFinite(Date.parse(result.since))))throw new Error('since must be a valid ISO UTC time');return result;}
