import {activityData} from './audit';
import {z} from 'zod';
import {modelName,slugFor,number,ngnk} from './metrics';
import {compareAmounts} from './insights';
import type {Epoch,Participant,Block,Proposal,Model,ModelStat,Endpoint} from './types';
export const scalar=z.union([z.string(),z.number()]).transform(String);
export const integer=scalar.transform(Number).refine(n=>Number.isSafeInteger(n)&&n>=0);
export const record=z.record(z.string(),z.unknown());
export function epochData(data:unknown):Epoch {const d=z.object({block_height:integer,latest_epoch:z.object({index:integer}),phase:z.string(),epoch_stages:record}).parse(data);const s=d.epoch_stages,start=integer.parse(s.poc_start),end=integer.parse(s.next_poc_start);if(end<=start)throw new Error('Invalid epoch interval');const names=[['Proof of compute','poc_start'],['Validation','poc_validation_start'],['Validator selection','poc_validation_end'],['Inference','set_new_validators'],['Next epoch','next_poc_start']];return {id:d.latest_epoch.index,height:d.block_height,phase:d.phase,start,end,progress:Math.max(0,Math.min(100,(d.block_height-start)/(end-start)*100)),remaining:Math.max(0,end-d.block_height),boundaries:names.map(([label,key])=>({label,height:integer.parse(s[key])}))};}
export function participantData(data:unknown):Participant[]{const d=z.object({active_participants:z.object({participants:z.array(z.object({index:z.string(),weight:scalar.refine(v=>/^\d{1,80}$/.test(v),'Expected unsigned integer weight'),models:z.array(z.string()).default([]),ml_nodes:z.array(record).optional()}))}),excluded_participants:z.array(z.object({address:z.string(),reason:z.string().optional()})).default([])}).parse(data);const excluded=new Map(d.excluded_participants.map(x=>[x.address,x.reason??'Excluded by source']));return d.active_participants.participants.map(p=>{const ids=new Set<string>();for(const group of p.ml_nodes??[])for(const node of Array.isArray(group.ml_nodes)?group.ml_nodes:[]){const n=record.parse(node);if(typeof n.node_id==='string')ids.add(n.node_id);}return {address:p.index,weight:p.weight,models:p.models,nodes:p.ml_nodes===undefined?null:ids.size,nodeIds:[...ids],excluded:excluded.has(p.index),reason:excluded.get(p.index)??null};}).sort((a,b)=>compareAmounts(b.weight,a.weight));}
export function blockData(data:unknown):Block[]{const d=z.object({blocks:z.array(z.object({block_height:integer,block_time:z.string(),num_txs:integer,total_gas_used:scalar}))}).parse(data);const rows=d.blocks.map(b=>({height:b.block_height,time:b.block_time.includes('T')?b.block_time:b.block_time.replace(' ','T')+'Z',transactions:b.num_txs,gas:b.total_gas_used}));activityData(rows);return rows.sort((a,b)=>b.height-a.height);}
export function proposalData(data:unknown):Proposal[]{const d=z.object({proposals:z.array(record)}).parse(data);return d.proposals.map(p=>{const tally=record.catch({}).parse(p.final_tally_result);return {id:scalar.parse(p.id),title:String(p.title??'Proposal '+p.id),summary:String(p.summary??''),status:String(p.status??'unknown').replace('PROPOSAL_STATUS_',''),votingStart:String(p.voting_start_time??''),votingEnd:String(p.voting_end_time??''),messages:(Array.isArray(p.messages)?p.messages:[]).map(x=>String(record.parse(x)['@type']??'Unknown message')),yes:String(tally.yes_count??'0'),no:String(tally.no_count??'0'),abstain:String(tally.abstain_count??'0')};});}
export function modelData(models:unknown,capabilities:unknown,pricing:unknown):Model[]{const m=z.object({data:z.array(z.object({id:z.string(),owned_by:z.string().optional()}))}).parse(models);const caps=z.object({models:z.array(record)}).safeParse(capabilities),rates=z.object({models:z.array(record)}).safeParse(pricing);return m.data.map(x=>{const c=caps.success?caps.data.models.find(a=>a.id===x.id):undefined,r=rates.success?rates.data.models.find(a=>a.model_id===x.id):undefined;return {id:x.id,name:modelName(x.id),slug:slugFor(x.id),provider:x.owned_by??'OpenBroker',context:number(c?.max_model_len??c?.context_length),output:number(c?.max_output_tokens),vram:number(c?.v_ram_gb),tools:typeof c?.supports_tools==='boolean'?c.supports_tools:null,reasoning:typeof c?.supports_reasoning==='boolean'?c.supports_reasoning:null,price:r?.usd_per_million_tokens==null?null:scalar.refine(v=>/^\d{1,80}(\.\d{1,40})?$/.test(v),'Invalid advertised price').parse(r.usd_per_million_tokens),ngonka:r?.ngonka_per_token==null?null:String(r.ngonka_per_token),hfRepo:typeof c?.hf_repo==='string'?c.hf_repo:null,hfCommit:typeof c?.hf_commit==='string'?c.hf_commit:null};});}
export function statsData(data:unknown):ModelStat[]{const d=z.object({stats_models:z.array(z.object({model:z.string(),ai_tokens:scalar,inferences:scalar}))}).parse(data);return d.stats_models.map(s=>({model:s.model,tokens:s.ai_tokens,requests:s.inferences}));}
export function coinField(data:unknown,path:string[]):string|null {let v:unknown=data;for(const k of path){if(!v||typeof v!=='object')return null;v=(v as Record<string,unknown>)[k];}try{return v===undefined?null:ngnk(scalar.parse(v));}catch{return null;}}
export function catalogData(data:unknown):Endpoint[]{const d=z.object({groups:z.array(z.object({label:z.string(),endpoints:z.array(z.object({method:z.string(),path:z.string().startsWith('/'),description:z.string(),params:z.string().optional(),cache:z.string().optional()}))}))}).parse(data);return d.groups.flatMap(g=>g.endpoints.map(e=>({...e,group:g.label,params:e.params??'',cache:e.cache??'Not specified'})));}
export function hardwareData(data:unknown,participants:Participant[]){const schema=z.object({nodes:z.array(z.object({participant:z.string(),hardware_nodes:z.array(z.object({local_id:z.string(),hardware:z.array(z.object({type:z.string(),count:integer}))}))}))});const d=schema.parse(data),members=new Map(participants.map(p=>[p.address,new Set(p.nodeIds)])),seen=new Map<string,string>(),totals=new Map<string,number>();for(const p of d.nodes){const ids=members.get(p.participant);if(!ids)continue;for(const n of p.hardware_nodes){if(!ids.has(n.local_id))continue;const key=p.participant+':'+n.local_id,fingerprint=JSON.stringify(n.hardware);if(seen.has(key)){if(seen.get(key)!==fingerprint)throw new Error('Conflicting hardware registrations');continue;}seen.set(key,fingerprint);for(const h of n.hardware)totals.set(h.type,(totals.get(h.type)??0)+h.count);}}return [...totals].map(([model,count])=>({model,count})).sort((a,b)=>b.count-a.count);}
