import {activityData} from './audit';
import {z} from 'zod';
import {modelName,slugFor,number,ngnk} from './metrics';
import {compareAmounts} from './insights';
import type {Epoch,Participant,ParticipantStat,Market,Block,Proposal,Model,ModelStat,Endpoint,GovernanceModel,PocModelParam,DevshardVersion} from './types';
export const scalar=z.union([z.string(),z.number()]).transform(String);
export const integer=scalar.transform(Number).refine(n=>Number.isSafeInteger(n)&&n>=0);
export const record=z.record(z.string(),z.unknown());
export const amount=scalar.refine(v=>/^\d{1,80}(\.\d{1,40})?$/.test(v),'Expected nonnegative decimal');
function exactExponent(value:unknown):string|null{const p=z.object({value:scalar,exponent:z.coerce.number().int().min(-30).max(30)}).safeParse(value);if(!p.success)return null;const negative=p.data.value.startsWith('-'),digits=(negative?p.data.value.slice(1):p.data.value).replace(/^0+(?=\d)/,'');if(!/^\d+$/.test(digits))return null;const e=p.data.exponent;if(e>=0)return (negative?'-':'')+digits+'0'.repeat(e);const places=-e,padded=digits.padStart(places+1,'0'),point=padded.length-places;return (negative?'-':'')+padded.slice(0,point)+'.'+padded.slice(point);}
export function epochData(data:unknown):Epoch {const d=z.object({block_height:integer,latest_epoch:z.object({index:integer}),phase:z.string(),epoch_stages:record}).parse(data);const s=d.epoch_stages,start=integer.parse(s.poc_start),end=integer.parse(s.next_poc_start);if(end<=start)throw new Error('Invalid epoch interval');const names=[['Proof of compute','poc_start'],['Validation','poc_validation_start'],['Validator selection','poc_validation_end'],['Inference','set_new_validators'],['Next epoch','next_poc_start']];return {id:d.latest_epoch.index,height:d.block_height,phase:d.phase,start,end,progress:Math.max(0,Math.min(100,(d.block_height-start)/(end-start)*100)),remaining:Math.max(0,end-d.block_height),boundaries:names.map(([label,key])=>({label,height:integer.parse(s[key])}))};}
export function participantData(data:unknown):Participant[]{const d=z.object({active_participants:z.object({participants:z.array(z.object({index:z.string(),weight:scalar.refine(v=>/^\d{1,80}$/.test(v),'Expected unsigned integer weight'),models:z.array(z.string()).default([]),ml_nodes:z.array(record).optional()}))}),excluded_participants:z.array(z.object({address:z.string(),reason:z.string().optional()})).default([])}).parse(data);const excluded=new Map(d.excluded_participants.map(x=>[x.address,x.reason??'Excluded by source']));return d.active_participants.participants.map(p=>{const ids=new Set<string>();for(const group of p.ml_nodes??[])for(const node of Array.isArray(group.ml_nodes)?group.ml_nodes:[]){const n=record.parse(node);if(typeof n.node_id==='string')ids.add(n.node_id);}return {address:p.index,weight:p.weight,models:p.models,nodes:p.ml_nodes===undefined?null:ids.size,nodeIds:[...ids],excluded:excluded.has(p.index),reason:excluded.get(p.index)??null};}).sort((a,b)=>compareAmounts(b.weight,a.weight));}
export function participantStatsData(data:unknown):ParticipantStat[]{const d=z.object({participants_stats:z.array(z.object({account_address:z.string(),operator_address:z.string().nullish(),reputation:scalar.nullish(),earned_coins_current_epoch:scalar.nullish(),rewarded_coins_latest_epoch:scalar.nullish(),epochs_completed:scalar.nullish()}).passthrough()).default([])}).parse(data);return d.participants_stats.map(p=>({address:p.account_address,operatorAddress:p.operator_address??null,reputation:p.reputation==null?null:Number(p.reputation),earnedCoinsCurrentEpoch:p.earned_coins_current_epoch??null,rewardedCoinsLatestEpoch:p.rewarded_coins_latest_epoch??null,epochsCompleted:p.epochs_completed==null?null:Number(p.epochs_completed)}));}
export function dexData(data:unknown):Market|null{const schema=z.object({pairs:z.array(z.object({dexId:z.string(),pairAddress:z.string().nullish(),baseToken:z.object({symbol:z.string(),name:z.string(),address:z.string()}).nullish(),quoteToken:z.object({symbol:z.string()}).nullish(),priceUsd:scalar.nullish(),marketCap:scalar.nullish(),fdv:scalar.nullish(),liquidity:z.object({usd:scalar.nullish()}).nullish(),volume:z.object({h24:scalar.nullish()}).nullish(),priceChange:z.object({h24:scalar.nullish()}).nullish()}).passthrough()).default([])});const p=schema.safeParse(data);if(!p.success)return null;const best=p.data.pairs.slice().sort((a,b)=>(parseFloat(b.liquidity?.usd??'0')||0)-(parseFloat(a.liquidity?.usd??'0')||0))[0];if(!best)return null;return {symbol:best.baseToken?.symbol??'GNK',name:best.baseToken?.name??'Gonka',dex:best.dexId??'uniswap',pairAddress:best.pairAddress??null,priceUsd:best.priceUsd??null,marketCap:best.marketCap??null,fdv:best.fdv??null,liquidity:best.liquidity?.usd??null,volume24h:best.volume?.h24??null,priceChange24h:best.priceChange?.h24??null,baseToken:best.baseToken?.address??null,quoteToken:best.quoteToken?.symbol??null};}
export function blockData(data:unknown):Block[]{const d=z.object({blocks:z.array(z.object({block_height:integer,block_time:z.string(),num_txs:integer,total_gas_used:scalar}))}).parse(data);const rows=d.blocks.map(b=>({height:b.block_height,time:b.block_time.includes('T')?b.block_time:b.block_time.replace(' ','T')+'Z',transactions:b.num_txs,gas:b.total_gas_used}));activityData(rows);return rows.sort((a,b)=>b.height-a.height);}
export function proposalData(data:unknown):Proposal[]{const d=z.object({proposals:z.array(record)}).parse(data);return d.proposals.map(p=>{const tally=record.catch({}).parse(p.final_tally_result);return {id:scalar.parse(p.id),title:String(p.title??'Proposal '+p.id),summary:String(p.summary??''),status:String(p.status??'unknown').replace('PROPOSAL_STATUS_',''),votingStart:String(p.voting_start_time??''),votingEnd:String(p.voting_end_time??''),messages:(Array.isArray(p.messages)?p.messages:[]).map(x=>String(record.parse(x)['@type']??'Unknown message')),yes:String(tally.yes_count??'0'),no:String(tally.no_count??'0'),abstain:String(tally.abstain_count??'0')};});}
export function modelData(models:unknown,capabilities:unknown,pricing:unknown):Model[]{const m=z.object({data:z.array(z.object({id:z.string(),owned_by:z.string().optional()}))}).parse(models);const caps=z.object({models:z.array(record)}).safeParse(capabilities),rates=z.object({models:z.array(record)}).safeParse(pricing);return m.data.map(x=>{const c=caps.success?caps.data.models.find(a=>a.id===x.id):undefined,r=rates.success?rates.data.models.find(a=>a.model_id===x.id):undefined;return {id:x.id,name:modelName(x.id),slug:slugFor(x.id),provider:x.owned_by??'OpenBroker',context:number(c?.max_model_len??c?.context_length),output:number(c?.max_output_tokens),vram:number(c?.v_ram_gb),tools:typeof c?.supports_tools==='boolean'?c.supports_tools:null,reasoning:typeof c?.supports_reasoning==='boolean'?c.supports_reasoning:null,price:r?.usd_per_million_tokens==null?null:amount.parse(r.usd_per_million_tokens),ngonka:r?.ngonka_per_token==null?null:String(r.ngonka_per_token),hfRepo:typeof c?.hf_repo==='string'?c.hf_repo:null,hfCommit:typeof c?.hf_commit==='string'?c.hf_commit:null};});}
export function networkModelIds(data:unknown):string[]{return z.object({data:z.array(z.object({id:z.string()}))}).parse(data).data.map(x=>x.id);}
export function governanceModelData(data:unknown):GovernanceModel[]{const d=z.object({models:z.array(record)}).parse(data);return d.models.map(m=>({id:z.string().parse(m.id),hfRepo:typeof m.hf_repo==='string'?m.hf_repo:null,hfCommit:typeof m.hf_commit==='string'?m.hf_commit:null,vram:number(m.v_ram),unitsOfComputePerToken:m.units_of_compute_per_token==null?null:scalar.parse(m.units_of_compute_per_token),throughputPerNonce:m.throughput_per_nonce==null?null:scalar.parse(m.throughput_per_nonce)}));}
export function versionsData(data:unknown):Record<string,string>{const root=record.parse(data),out:Record<string,string>={};const visit=(prefix:string,value:unknown)=>{if(['string','number','boolean'].includes(typeof value)){if(prefix)out[prefix]=String(value);return;}if(value&&typeof value==='object'&&!Array.isArray(value))for(const [key,child] of Object.entries(value as Record<string,unknown>))visit(prefix?prefix+'.'+key:key,child);};visit('',root);return out;}
export function protocolParamsData(data:unknown):{protocol:Record<string,string>;pocModels:PocModelParam[];devshardVersions:DevshardVersion[]}{const params=z.object({params:record}).parse(data).params,protocol:Record<string,string>={};for(const [group,value] of Object.entries(params)){const fields=record.safeParse(value);if(!fields.success)continue;let actual=fields.data;if(group==='epoch_params'&&actual.epoch_params){const nested=record.safeParse(actual.epoch_params);if(nested.success)actual=nested.data;}for(const [key,raw] of Object.entries(actual)){if(['string','number','boolean'].includes(typeof raw))protocol[group+'.'+key]=String(raw);else{const decimal=exactExponent(raw);if(decimal!==null)protocol[group+'.'+key]=decimal;}}}
 const pocRoot=record.safeParse(params.poc_params),pocModels:PocModelParam[]=[];if(pocRoot.success&&Array.isArray(pocRoot.data.models))for(const raw of pocRoot.data.models){const m=record.safeParse(raw);if(!m.success||typeof m.data.model_id!=='string')continue;pocModels.push({id:m.data.model_id,seqLen:m.data.seq_len==null?null:scalar.parse(m.data.seq_len),weightScaleFactor:exactExponent(m.data.weight_scale_factor),penaltyStartEpoch:m.data.penalty_start_epoch==null?null:scalar.parse(m.data.penalty_start_epoch)});}
 const devRoot=record.safeParse(params.devshard_escrow_params),devshardVersions:DevshardVersion[]=[];if(devRoot.success&&Array.isArray(devRoot.data.approved_versions))for(const raw of devRoot.data.approved_versions){const v=record.safeParse(raw);if(!v.success||typeof v.data.name!=='string')continue;devshardVersions.push({name:v.data.name,binary:typeof v.data.binary==='string'?v.data.binary:null,sha256:typeof v.data.sha256==='string'?v.data.sha256:null});}
 return {protocol,pocModels,devshardVersions};}
export function statsData(data:unknown):ModelStat[]{const d=z.object({stats_models:z.array(z.object({model:z.string(),ai_tokens:scalar,inferences:scalar}))}).parse(data);return d.stats_models.map(s=>({model:s.model,tokens:s.ai_tokens,requests:s.inferences}));}
export function coinField(data:unknown,path:string[]):string|null {let v:unknown=data;for(const k of path){if(!v||typeof v!=='object')return null;v=(v as Record<string,unknown>)[k];}try{return v===undefined?null:ngnk(scalar.parse(v));}catch{return null;}}
function endpointNamespace(path:string):Endpoint['namespace']{if(path.startsWith('/chain-rpc/'))return 'chain-rpc';if(path.startsWith('/chain-api/'))return 'chain-api';if(path.startsWith('/api/ch/'))return 'api/ch';if(path.startsWith('/v1/')||path.startsWith('/v2/'))return 'v1';return 'other';}
export function catalogDeclaredTotal(data:unknown):number|null{const v=record.parse(data).total_endpoints;return v==null?null:integer.parse(v);}
export function catalogData(data:unknown):Endpoint[]{const d=z.object({groups:z.array(z.object({label:z.string(),endpoints:z.array(z.object({method:z.string(),path:z.string().startsWith('/'),description:z.string(),params:z.string().optional(),cache:z.string().optional()}))}))}).parse(data);return d.groups.flatMap(g=>g.endpoints.map(e=>({...e,group:g.label,params:e.params??'',cache:e.cache??'Not specified',namespace:endpointNamespace(e.path),readOnly:e.method.toUpperCase()==='GET'})));}
export function hardwareData(data:unknown,participants:Participant[]){const schema=z.object({nodes:z.array(z.object({participant:z.string(),hardware_nodes:z.array(z.object({local_id:z.string(),hardware:z.array(z.object({type:z.string(),count:integer}))}))}))});const d=schema.parse(data),members=new Map(participants.map(p=>[p.address,new Set(p.nodeIds)])),seen=new Map<string,string>(),totals=new Map<string,number>();for(const p of d.nodes){const ids=members.get(p.participant);if(!ids)continue;for(const n of p.hardware_nodes){if(!ids.has(n.local_id))continue;const key=p.participant+':'+n.local_id,fingerprint=JSON.stringify(n.hardware);if(seen.has(key)){if(seen.get(key)!==fingerprint)throw new Error('Conflicting hardware registrations');continue;}seen.set(key,fingerprint);for(const h of n.hardware)totals.set(h.type,(totals.get(h.type)??0)+h.count);}}return [...totals].map(([model,count])=>({model,count})).sort((a,b)=>b.count-a.count);}
