import {spawn} from 'node:child_process';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
await mkdir('artifacts/screenshots',{recursive:true});
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3101'],{env:{...process.env,DATA_MODE:'snapshot',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});
const log=createWriteStream('artifacts/revamp-server.log');server.stdout.pipe(log);server.stderr.pipe(log);
const base='http://127.0.0.1:3101';let browser;
const report={startedAt:new Date().toISOString(),mode:'real retained public observation',checks:[],accessibility:[],runtimeErrors:[],skipped:[]};
try{
 let ready=false;for(let i=0;i<60;i++){try{const r=await fetch(base+'/api/v1/openapi');if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,1000));}assert.ok(ready,'Production server ready');
 const snapshot=JSON.parse(await readFile('data/snapshot.json','utf8'));browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const page=await context.newPage();page.on('pageerror',e=>report.runtimeErrors.push(e.message));
 await page.goto(base+'/',{waitUntil:'networkidle'});await expect(page.locator('.dashboard-kpis .metric')).toHaveCount(6);await expect(page.getByRole('heading',{name:'Gonka, at a glance.'})).toBeVisible();
 const source=page.locator('.kpi-tile .source-note').first();await source.locator('summary').click();await expect(source.getByRole('link',{name:'Inspect upstream source'})).toBeVisible();assert.equal(await page.locator('.kpi-tile').first().evaluate(el=>getComputedStyle(el).overflow),'visible');await source.locator('summary').click();report.checks.push('Six source-qualified KPIs with unclipped provenance');
 if(snapshot.hardware.length){await page.getByRole('button',{name:'View gpu mix data',exact:true}).click();await expect(page.locator('caption').filter({hasText:'GPU mix exact values'})).toHaveCount(1);const event=page.waitForEvent('download');await page.getByRole('button',{name:'Export GPU mix CSV',exact:true}).click();assert.equal((await event).suggestedFilename(),'gpu-mix.csv');await page.getByRole('button',{name:'Hide gpu mix data',exact:true}).click();report.checks.push('GPU chart has exact table and CSV export');}else report.skipped.push('GPU chart interaction: no observed hardware rows');
 if(snapshot.models.length){await page.getByRole('button',{name:'Advertised price',exact:true}).click();await expect(page.getByRole('figure',{name:'Model pricing'})).toBeVisible();await page.getByRole('button',{name:'Context window',exact:true}).click();await expect(page.getByRole('figure',{name:'Model context'})).toBeVisible();report.checks.push('Model comparison chart measure switch');}
 await page.getByRole('checkbox',{name:'Omit members marked excluded'}).check();await expect(page.getByRole('checkbox',{name:'Omit members marked excluded'})).toBeChecked();await page.getByRole('checkbox',{name:'Omit members marked excluded'}).uncheck();report.checks.push('Model footprint has explicit scope control');
 if(snapshot.participants.length){await page.getByRole('button',{name:'View concentration data',exact:true}).click();await expect(page.locator('caption').filter({hasText:'Exact declared-weight concentration'})).toHaveCount(1);await page.getByRole('button',{name:'Hide concentration data',exact:true}).click();report.checks.push('Declared-weight cumulative chart and exact table');}
 await page.goto(base+'/models',{waitUntil:'networkidle'});await page.getByRole('textbox',{name:'Search model catalog'}).fill('missing-model-xyz');await expect(page.getByRole('heading',{name:'No models match this view'})).toBeVisible();assert.ok(new URL(page.url()).searchParams.has('q'));await page.getByRole('button',{name:'Reset filters',exact:true}).click();
 if(snapshot.models.length){await expect(page.locator('.catalog-card')).toHaveCount(snapshot.models.length);await page.getByRole('button',{name:'Model table',exact:true}).click();assert.equal(new URL(page.url()).searchParams.get('view'),'table');await expect(page.locator('caption').filter({hasText:'Filtered Gonka model catalog'})).toHaveCount(1);await page.getByRole('button',{name:'Model cards',exact:true}).click();for(const model of snapshot.models.slice(0,2))await page.getByRole('button',{name:'Compare '+model.name,exact:true}).click();const selected=Math.min(2,snapshot.models.length);await expect(page.locator('.model-comparison-table thead th')).toHaveCount(selected+1);assert.equal(new URL(page.url()).searchParams.getAll('compare').length,selected);await page.reload({waitUntil:'networkidle'});await expect(page.locator('.model-comparison-table thead th')).toHaveCount(selected+1);await page.screenshot({path:'artifacts/screenshots/models-comparison-1440.png',fullPage:true});const event=page.waitForEvent('download');await page.getByRole('button',{name:'Export filtered',exact:true}).click();assert.equal((await event).suggestedFilename(),'gonka-models.csv');await page.getByRole('button',{name:'Clear comparison',exact:true}).click();await expect(page.locator('.model-comparison-table')).toHaveCount(0);report.checks.push('Model search, card/table switch, persisted comparison, reset and CSV');}else report.skipped.push('Model comparison interaction: catalog unavailable');
 await page.goto(base+'/cost-lab');await page.getByRole('button',{name:'Document review',exact:true}).click();await page.getByLabel('Number of requests',{exact:true}).fill('2');const prompt=await page.getByLabel('Prompt tokens / request',{exact:true}).inputValue(),completion=await page.getByLabel('Completion tokens / request',{exact:true}).inputValue();const r=await fetch(base+`/api/v1/simulate-cost?prompt=${prompt}&completion=${completion}&requests=2&attempts=1.5`);const result=await r.json();assert.equal(result.data.tokens,((BigInt(prompt)+BigInt(completion))*2n).toString());await expect(page.getByTestId('cost-tokens')).toHaveText('22K tokens');await expect(page.getByRole('figure',{name:'Retry cost scenarios'})).toBeVisible();report.checks.push('Realistic workload presets and exact API/UI cost agreement');
 await page.goto(base+'/learn',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Research hosting',exact:true}).click();await expect(page.getByRole('heading',{name:'Research hosting before committing hardware'})).toBeVisible();await page.getByText('Why is there no GNK market cap?',{exact:true}).click();await expect(page.getByText('The connected supply endpoint reports issued native supply',{exact:false})).toBeVisible();report.checks.push('Learning paths and plain-language FAQ disclosures');
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1050});for(const route of ['/','/models','/learn','/cost-lab']){await page.goto(base+route,{waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,route+' overflow at '+width);await expect(page.locator('main h1')).toHaveCount(1);if(width===1440||width===390)await page.screenshot({path:`artifacts/screenshots/${route==='/'?'overview-revamp':route.slice(1)+'-revamp'}-${width}.png`,fullPage:true});if(width===1440&&route==='/')await page.screenshot({path:'artifacts/screenshots/overview-revamp-desktop.png',fullPage:false});}}
 report.checks.push('Revamped pages at desktop/tablet/mobile without page overflow');await page.setViewportSize({width:1440,height:1050});
 for(const theme of ['dark','light']){await page.goto(base+'/');if(await page.locator('html').getAttribute('data-theme')!==theme)await page.getByRole('button',{name:'Toggle color theme'}).click();for(const route of ['/','/models','/learn','/cost-lab']){await page.goto(base+route,{waitUntil:'networkidle'});const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.accessibility.push({route,theme,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});}if(theme==='light'){await page.goto(base+'/');await page.screenshot({path:'artifacts/screenshots/overview-revamp-light.png',fullPage:false});}}
 assert.equal(report.runtimeErrors.length,0,'No browser exceptions');assert.equal(report.accessibility.flatMap(r=>r.violations).length,0,'No automated accessibility findings in selected new views');report.result='passed';
}catch(error){report.result='failed';report.error=error.stack??String(error);console.error(error);process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();await writeFile('artifacts/revamp-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser?.close();server.kill('SIGTERM');log.end();}
