import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
await mkdir('artifacts/screenshots',{recursive:true});
const log=createWriteStream('artifacts/workload-server.log');
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3103'],{env:{...process.env,DATA_MODE:'snapshot',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});server.stdout.pipe(log);server.stderr.pipe(log);
const base='http://127.0.0.1:3103';let browser;const report={checks:[],accessibility:[],errors:[],startedAt:new Date().toISOString()};
try{
 let ready=false;for(let i=0;i<60;i++){try{if((await fetch(base+'/api/v1/openapi')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,1000));}assert.ok(ready);
 const schema=await (await fetch(base+'/api/v1/openapi')).json();assert.ok(Object.keys(schema.paths).length>=21);
 const r=await fetch(base+'/api/v1/context-plan?prompt=8000&completion=2000');assert.equal(r.status,200);const plan=await r.json();assert.ok(Array.isArray(plan.data.plans));for(const p of plan.data.plans)assert.equal(p.total,'10000');
 for(const query of ['prompt=-1','prompt=1e6','prompt=1000000001','prompt=1&prompt=2','url=https://example.com'])assert.equal((await fetch(base+'/api/v1/context-plan?'+query)).status,400);
 assert.equal((await fetch(base+'/api/v1/context-plan?prompt=&completion=')).status,200);assert.equal((await fetch(base+'/api/v1/context-plan?prompt=0000000000008')).status,200);
 const composition=await (await fetch(base+'/api/v1/composition')).json();if(composition.data.membership){const m=composition.data.membership;assert.equal(m.total,m.notMarkedExcluded+m.markedExcluded);}report.checks.push('Both new APIs and bounded query validation');
 browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 await page.goto(base+'/workload?prompt=1000&completion=200',{waitUntil:'networkidle'});await expect(page.getByTestId('context-total')).toContainText('1,200');await page.getByRole('button',{name:'Document review',exact:true}).click();await expect(page.getByTestId('context-total')).toContainText('36,000');await expect(page.getByTestId('context-card')).toHaveCount(plan.data.plans.length);
 await page.getByLabel('Prompt tokens, including overhead',{exact:true}).fill('-1');await expect(page.locator('main').getByRole('alert')).toContainText('whole-token');await expect(page.getByTestId('context-card')).toHaveCount(0);await page.getByRole('button',{name:'Chat',exact:true}).click();await expect(page.getByTestId('context-total')).toContainText('5,000');
 if(plan.data.plans.length){const event=page.waitForEvent('download');await page.getByRole('button',{name:'Export context comparison'}).click();assert.equal((await event).suggestedFilename(),'gonka-context-plan.csv');}report.checks.push('Context presets, URL input, validation and export');
 await page.goto(base+'/');if(composition.data.governance?.returned){await page.getByRole('button',{name:'View proposal statuses data',exact:true}).click();await expect(page.locator('caption').filter({hasText:'Proposal statuses exact values'})).toHaveCount(1);}await page.goto(base+'/network');if(composition.data.membership)await expect(page.getByRole('figure',{name:'Membership status'})).toBeVisible();report.checks.push('New source-derived composition charts');
 await page.goto(base+'/learn');await expect(page.getByRole('heading',{name:'OpenBroker: read the bill, not just the headline rate'})).toBeVisible();await expect(page.getByText('Text tokens and Gonka AI Tokens',{exact:true})).toBeVisible();report.checks.push('Provider accounting content and precise glossary');
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1050});for(const route of ['/workload','/network','/learn','/']){await page.goto(base+route,{waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,route+' overflow at '+width);await expect(page.locator('main h1')).toHaveCount(1);if(width===1440||width===390)await page.screenshot({path:`artifacts/screenshots/${route==='/'?'overview-complete':route.slice(1)+'-complete'}-${width}.png`,fullPage:true});if(width===1440&&route==='/')await page.screenshot({path:'artifacts/screenshots/overview-complete-desktop.png',fullPage:false});}}
 report.checks.push('Desktop/tablet/mobile render and overflow');await page.setViewportSize({width:1440,height:1050});
 for(const theme of ['dark','light']){await page.goto(base+'/workload');if(await page.locator('html').getAttribute('data-theme')!==theme)await page.getByRole('button',{name:'Toggle color theme'}).click();for(const route of ['/workload','/network','/learn','/']){await page.goto(base+route,{waitUntil:'networkidle'});const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.accessibility.push({route,theme,violations:a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});}}
 assert.equal(report.accessibility.flatMap(r=>r.violations).length,0,'No axe violations in new views');assert.equal(report.errors.length,0);report.result='passed';
}catch(e){report.result='failed';report.error=String(e.stack??e);console.error(e);process.exitCode=1;}finally{report.finishedAt=new Date().toISOString();await writeFile('artifacts/workload-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser?.close();server.kill('SIGTERM');log.end();}
